"""
Maintenance data for all 55 SKUs.
Generated by Claude — zh+en complete, ms placeholders.
"""

MAINTENANCE = {

# ========================================
#  Cardio (CD-001 ~ CD-005)
# ========================================

"CD-001": {
    "badge": "full-kit",
    "badge_text": "Full spare parts kit shipped with equipment",
    "badge_text_zh": "全套备件已随货配送",
    "badge_text_ms": "",
    "spare_parts": [
        {"name":"Running Belt","name_zh":"跑带","name_ms":"","qty":"2 belts per 5 units","qty_zh":"每5台备2条","qty_ms":"","cycle":"18-24 months","cycle_zh":"18-24个月","cycle_ms":""},
        {"name":"Drive Belt","name_zh":"驱动皮带","name_ms":"","qty":"2 belts per 5 units","qty_zh":"每5台备2条","qty_ms":"","cycle":"24-36 months","cycle_zh":"24-36个月","cycle_ms":""},
        {"name":"Running Deck","name_zh":"跑板","name_ms":"","qty":"1 per 5 units","qty_zh":"每5台备1块","qty_ms":"","cycle":"24-36 months","cycle_zh":"24-36个月","cycle_ms":""},
        {"name":"Motor Carbon Brush","name_zh":"电机碳刷","name_ms":"","qty":"1 pair per unit","qty_zh":"每台1对","qty_ms":"","cycle":"12-18 months","cycle_zh":"12-18个月","cycle_ms":""},
        {"name":"Safety Key","name_zh":"安全钥匙","name_ms":"","qty":"2 per unit","qty_zh":"每台2个","qty_ms":"","cycle":"Replace when lost/damaged","cycle_zh":"丢失/损坏即换","cycle_ms":""},
        {"name":"Main Control Board","name_zh":"主控板","name_ms":"","qty":"1 per 5 units","qty_zh":"5台共备1块","qty_ms":"","cycle":"Emergency spare","cycle_zh":"故障应急","cycle_ms":""},
        {"name":"LED Display Panel","name_zh":"LED显示面板","name_ms":"","qty":"1 per 5 units","qty_zh":"5台共备1块","qty_ms":"","cycle":"Emergency spare","cycle_zh":"故障应急","cycle_ms":""},
        {"name":"Roller Bearings","name_zh":"前后滚筒轴承","name_ms":"","qty":"2 sets per 5 units","qty_zh":"每5台备2套","qty_ms":"","cycle":"36+ months","cycle_zh":"36个月+","cycle_ms":""},
        {"name":"Side Rail Anti-slip Strip","name_zh":"侧边条防滑贴","name_ms":"","qty":"3 pairs per 5 units","qty_zh":"每5台备3对","qty_ms":"","cycle":"12 months","cycle_zh":"12个月","cycle_ms":""},
        {"name":"Silicone Lubricant 500ml","name_zh":"硅油500ml","name_ms":"","qty":"5 bottles","qty_zh":"5瓶","qty_ms":"","cycle":"Consumable","cycle_zh":"消耗品","cycle_ms":""},
    ],
    "schedule": [
        {"interval":"Daily","interval_zh":"每天","interval_ms":"","action":"Clean dust and sweat from running belt surface","action_zh":"清洁跑带表面灰尘和汗渍","action_ms":""},
        {"interval":"Weekly","interval_zh":"每周","interval_ms":"","action":"Wipe motor housing, test safety key function","action_zh":"擦拭电机仓外壳，测试安全钥匙功能","action_ms":""},
        {"interval":"Monthly","interval_zh":"每月","interval_ms":"","action":"Apply silicone lubricant between belt and deck, check belt alignment and tension","action_zh":"跑带和跑板之间加硅油润滑，检查跑带居中和张紧度","action_ms":""},
        {"interval":"Quarterly","interval_zh":"每季度","interval_ms":"","action":"Inspect motor carbon brush wear, check all wiring terminals","action_zh":"检查电机碳刷磨损量，检查所有接线端子","action_ms":""},
        {"interval":"Semi-annually","interval_zh":"每半年","interval_ms":"","action":"Check front/rear roller bearings for noise, tighten all bolts","action_zh":"检查前后滚筒轴承有无异响，紧固全机螺栓","action_ms":""},
    ],
    "durability_note": "Commercial-grade 3.0HP DC motor designed for continuous operation, handles 12+ hours of daily use with ease. Digital signal control system prevents sudden stops and runaways. 100mm large-diameter rollers extend motor and belt lifespan.",
    "durability_note_zh": "商用级3.0Hp直流电机，连续运转设计，日均使用12小时以上无压力。数字信号控制系统杜绝急停和飞车，100mm大直径滚筒延长电机和跑带寿命。",
    "durability_note_ms": "",
},

"CD-002": {
    "badge": "full-kit",
    "badge_text": "Full spare parts kit shipped with equipment",
    "badge_text_zh": "全套备件已随货配送",
    "badge_text_ms": "",
    "spare_parts": [
        {"name":"Drive Belt","name_zh":"传动皮带","name_ms":"","qty":"1 per 2 units","qty_zh":"2台备1条","qty_ms":"","cycle":"24-36 months","cycle_zh":"24-36个月","cycle_ms":""},
        {"name":"Pedal Bearings","name_zh":"踏板轴承","name_ms":"","qty":"1 set per 2 units","qty_zh":"2台备1套","qty_ms":"","cycle":"24-36 months","cycle_zh":"24-36个月","cycle_ms":""},
        {"name":"Guide Rollers","name_zh":"导轨滑轮","name_ms":"","qty":"1 set (4 pcs) per 2 units","qty_zh":"2台备1套(4个)","qty_ms":"","cycle":"36 months","cycle_zh":"36个月","cycle_ms":""},
        {"name":"Pedal Anti-slip Pad","name_zh":"脚踏防滑垫","name_ms":"","qty":"2 pairs","qty_zh":"2对","qty_ms":"","cycle":"12 months","cycle_zh":"12个月","cycle_ms":""},
        {"name":"Heart Rate Sensor Pad","name_zh":"心率感应贴片","name_ms":"","qty":"2 pairs","qty_zh":"2对","qty_ms":"","cycle":"12-18 months","cycle_zh":"12-18个月","cycle_ms":""},
        {"name":"PU Foam Handle Cover","name_zh":"PU发泡扶手套","name_ms":"","qty":"1 pair","qty_zh":"1对","qty_ms":"","cycle":"24 months","cycle_zh":"24个月","cycle_ms":""},
    ],
    "schedule": [
        {"interval":"Daily","interval_zh":"每天","interval_ms":"","action":"Wipe sweat from handles and pedals (PU handles crack when soaked in sweat)","action_zh":"擦拭扶手和踏板上的汗渍（PU扶手被汗浸会开裂）","action_ms":""},
        {"interval":"Monthly","interval_zh":"每月","interval_ms":"","action":"Check all bolt tightness","action_zh":"检查所有螺栓紧固度","action_ms":""},
        {"interval":"Quarterly","interval_zh":"每季度","interval_ms":"","action":"Apply lithium grease to pedal bearings and linkage joints","action_zh":"给踏板轴承和连杆关节注入锂基润滑脂","action_ms":""},
        {"interval":"Semi-annually","interval_zh":"每半年","interval_ms":"","action":"Check drive belt tension and wear, inspect guide rollers","action_zh":"检查传动皮带松紧和磨损，检查导轨滑轮","action_ms":""},
    ],
    "durability_note": "Magnetic resistance system with zero-contact friction. Rear-wheel drive structure minimizes transmission loss. Designed for 8+ years of continuous commercial use.",
    "durability_note_zh": "磁控阻力系统无接触摩擦，后轮驱动结构传动损耗低，整机设计寿命8年以上商用连续使用。",
    "durability_note_ms": "",
},

"CD-003": {
    "badge": "full-kit",
    "badge_text": "Full spare parts kit shipped with equipment",
    "badge_text_zh": "全套备件已随货配送",
    "badge_text_ms": "",
    "spare_parts": [
        {"name":"Step Plate","name_zh":"踏步板","name_ms":"","qty":"4 plates","qty_zh":"备4块","qty_ms":"","cycle":"18-24 months","cycle_zh":"18-24个月","cycle_ms":""},
        {"name":"Step Chain","name_zh":"踏步链条","name_ms":"","qty":"1 chain","qty_zh":"备1条","qty_ms":"","cycle":"36 months","cycle_zh":"36个月","cycle_ms":""},
        {"name":"Drive Belt","name_zh":"驱动皮带","name_ms":"","qty":"1 belt","qty_zh":"备1条","qty_ms":"","cycle":"24-36 months","cycle_zh":"24-36个月","cycle_ms":""},
        {"name":"Main Shaft Bearings","name_zh":"主轴轴承","name_ms":"","qty":"1 set (2 pcs)","qty_zh":"备1套(2个)","qty_ms":"","cycle":"36 months","cycle_zh":"36个月","cycle_ms":""},
        {"name":"Chain Lube 250ml","name_zh":"链条润滑油250ml","name_ms":"","qty":"2 bottles","qty_zh":"2瓶","qty_ms":"","cycle":"Consumable","cycle_zh":"消耗品","cycle_ms":""},
        {"name":"Safety Sensor Switch","name_zh":"安全感应开关","name_ms":"","qty":"2 units","qty_zh":"2个","qty_ms":"","cycle":"Replace on failure","cycle_zh":"故障更换","cycle_ms":""},
        {"name":"Shell Screw Kit","name_zh":"外壳固定螺丝套装","name_ms":"","qty":"2 kits","qty_zh":"2套","qty_ms":"","cycle":"Replace when loose","cycle_zh":"松动即补","cycle_ms":""},
    ],
    "schedule": [
        {"interval":"Daily","interval_zh":"每天","interval_ms":"","action":"Clean step plate surfaces (dust in anti-slip grooves reduces traction)","action_zh":"清洁踏步板表面（防滑纹积尘影响摩擦力）","action_ms":""},
        {"interval":"Monthly","interval_zh":"每月","interval_ms":"","action":"Apply chain lubricant","action_zh":"给链条加专用链条油","action_ms":""},
        {"interval":"Quarterly","interval_zh":"每季度","interval_ms":"","action":"Check drive belt tension","action_zh":"检查驱动皮带张紧度","action_ms":""},
        {"interval":"Semi-annually","interval_zh":"每半年","interval_ms":"","action":"Full inspection of bearings and sprocket wear","action_zh":"全面检查轴承和链轮磨损情况","action_ms":""},
    ],
    "durability_note": "Injection-molded shell is one-piece formed, sturdy and resistant to deformation. Industrial-grade chain drive system designed for continuous operation at 160kg load.",
    "durability_note_zh": "注塑外壳一体成型，结实耐用不变形。工业级链条传动系统，设计承载160kg持续运转。",
    "durability_note_ms": "",
},

"CD-004": {
    "badge": "long-life",
    "badge_text": "Magnetic resistance · Ultra-low maintenance",
    "badge_text_zh": "磁控系统 · 极低维护",
    "badge_text_ms": "",
    "spare_parts": [
        {"name":"Drive Belt","name_zh":"传动皮带","name_ms":"","qty":"1 belt","qty_zh":"备1条","qty_ms":"","cycle":"36 months","cycle_zh":"36个月","cycle_ms":""},
        {"name":"Seat Rail Rollers","name_zh":"座椅滑轨滚轮","name_ms":"","qty":"1 set (4 pcs)","qty_zh":"备1套(4个)","qty_ms":"","cycle":"24 months","cycle_zh":"24个月","cycle_ms":""},
        {"name":"Seat Cover","name_zh":"座垫套","name_ms":"","qty":"1 pc","qty_zh":"备1个","qty_ms":"","cycle":"18-24 months","cycle_zh":"18-24个月","cycle_ms":""},
        {"name":"Pedal Strap","name_zh":"脚踏绑带","name_ms":"","qty":"2 pairs","qty_zh":"备2对","qty_ms":"","cycle":"12 months","cycle_zh":"12个月","cycle_ms":""},
    ],
    "schedule": [
        {"interval":"Daily","interval_zh":"每天","interval_ms":"","action":"Wipe sweat from seat and backrest","action_zh":"擦拭座椅和靠背汗渍","action_ms":""},
        {"interval":"Monthly","interval_zh":"每月","interval_ms":"","action":"Check seat rail smoothness","action_zh":"检查座椅滑轨顺滑度","action_ms":""},
        {"interval":"Quarterly","interval_zh":"每季度","interval_ms":"","action":"Apply grease to seat rail and pedal bearings","action_zh":"给滑轨和脚踏轴承加润滑脂","action_ms":""},
    ],
    "durability_note": "Magnetic resistance has zero physical contact and zero-wear resistance adjustment. Recumbent design keeps center of gravity low with even structural stress distribution. Virtually no failure points. Ideal for long-duration, high-frequency commercial use.",
    "durability_note_zh": "磁控阻力无物理接触，零磨损调阻。卧式设计重心低，机身结构受力均匀，整机几乎无故障点。适合长时间高频次商用。",
    "durability_note_ms": "",
},

"CD-005": {
    "badge": "long-life",
    "badge_text": "Pure mechanical · Minimal failure points",
    "badge_text_zh": "纯机械结构 · 极少故障",
    "badge_text_ms": "",
    "spare_parts": [
        {"name":"Drive Chain","name_zh":"传动链条","name_ms":"","qty":"1 chain","qty_zh":"备1条","qty_ms":"","cycle":"36 months","cycle_zh":"36个月","cycle_ms":""},
        {"name":"Pedal Strap/Clip","name_zh":"脚踏绑带/锁扣","name_ms":"","qty":"1 pair","qty_zh":"备1对","qty_ms":"","cycle":"12 months","cycle_zh":"12个月","cycle_ms":""},
        {"name":"Seat Cover","name_zh":"座垫套","name_ms":"","qty":"1 pc","qty_zh":"备1个","qty_ms":"","cycle":"18 months","cycle_zh":"18个月","cycle_ms":""},
        {"name":"Chain Lube 250ml","name_zh":"链条油250ml","name_ms":"","qty":"1 bottle","qty_zh":"1瓶","qty_ms":"","cycle":"Consumable","cycle_zh":"消耗品","cycle_ms":""},
    ],
    "schedule": [
        {"interval":"Weekly","interval_zh":"每周","interval_ms":"","action":"Clean fan blades (dust buildup affects air resistance uniformity)","action_zh":"风扇叶片清灰（积灰影响风阻均匀性）","action_ms":""},
        {"interval":"Monthly","interval_zh":"每月","interval_ms":"","action":"Lubricate drive chain","action_zh":"传动链条加油","action_ms":""},
        {"interval":"Quarterly","interval_zh":"每季度","interval_ms":"","action":"Tighten all bolts","action_zh":"紧固全车螺栓","action_ms":""},
    ],
    "durability_note": "The air bike has no electronics, no motor, no belt — resistance comes entirely from air. The simpler the structure, the more durable it is. This bike's failure rate is close to zero.",
    "durability_note_zh": "风阻单车没有电子元件、没有电机、没有皮带——阻力完全来自空气。结构越简单越耐用，这台车的故障率接近于零。",
    "durability_note_ms": "",
},

# ========================================
#  Pin-Loaded (FS-001 ~ FS-018)
# ========================================

"FS-001": {
    "badge": "full-kit",
    "badge_text": "Full spare parts kit shipped with equipment",
    "badge_text_zh": "全套备件已随货配送",
    "badge_text_ms": "",
    "spare_parts": [
        {"name":"Coated Steel Cable","name_zh":"包胶钢丝绳","name_ms":"","qty":"Cut from 50m bulk spool","qty_zh":"从50m散装绳裁切","qty_ms":"","cycle":"18-24 months","cycle_zh":"18-24个月","cycle_ms":""},
        {"name":"Pulley w/ Bearing","name_zh":"滑轮（含轴承）","name_ms":"","qty":"From universal parts stock","qty_zh":"从通用库取用","qty_ms":"","cycle":"24-36 months","cycle_zh":"24-36个月","cycle_ms":""},
        {"name":"Weight Pin","name_zh":"插片选择销","name_ms":"","qty":"From universal parts stock","qty_zh":"从通用库取用","qty_ms":"","cycle":"12 months","cycle_zh":"12个月","cycle_ms":""},
        {"name":"Guide Rod Bushing","name_zh":"导轨塑料衬套","name_ms":"","qty":"From universal parts stock","qty_zh":"从通用库取用","qty_ms":"","cycle":"12-18 months","cycle_zh":"12-18个月","cycle_ms":""},
        {"name":"Spherical Bearing","name_zh":"关节轴承","name_ms":"","qty":"From universal parts stock","qty_zh":"从通用库取用","qty_ms":"","cycle":"24-36 months","cycle_zh":"24-36个月","cycle_ms":""},
        {"name":"Handle Foam Grip","name_zh":"手柄海绵套","name_ms":"","qty":"From universal parts stock","qty_zh":"从通用库取用","qty_ms":"","cycle":"6-12 months","cycle_zh":"6-12个月","cycle_ms":""},
        {"name":"Seat Pad","name_zh":"座垫","name_ms":"","qty":"From universal parts stock","qty_zh":"从通用库取用","qty_ms":"","cycle":"18-24 months","cycle_zh":"18-24个月","cycle_ms":""},
    ],
    "schedule": [
        {"interval":"Daily","interval_zh":"每天","interval_ms":"","action":"Wipe sweat from seat pad and handles","action_zh":"擦拭座垫和把手汗渍","action_ms":""},
        {"interval":"Weekly","interval_zh":"每周","interval_ms":"","action":"Check weight pin spring return, visually inspect steel cable","action_zh":"检查插片选择销弹簧回弹，目视检查钢丝绳","action_ms":""},
        {"interval":"Monthly","interval_zh":"每月","interval_ms":"","action":"Apply white lithium grease to weight stack guide rods","action_zh":"配重片导轨涂白色锂基润滑脂","action_ms":""},
        {"interval":"Quarterly","interval_zh":"每季度","interval_ms":"","action":"Check pulley rotation smoothness, grease spherical bearings","action_zh":"检查滑轮转动顺滑度，给关节轴承注脂","action_ms":""},
        {"interval":"Semi-annually","interval_zh":"每半年","interval_ms":"","action":"Torque-wrench tighten all bolts, inspect cable coating","action_zh":"扭力扳手紧固全机螺栓，检查钢丝绳包胶层","action_ms":""},
    ],
    "durability_note": "All spare parts come from the universal parts stock. Any single component failure can be quickly replaced on-site — no waiting for overseas shipments.",
    "durability_note_zh": "全机备件均来自通用备件库，任何单一零件损坏均可现场快速更换，无需等待海外发货。",
    "durability_note_ms": "",
},

"FS-002": {
    "badge": "full-kit",
    "badge_text": "Full spare parts kit shipped with equipment",
    "badge_text_zh": "全套备件已随货配送",
    "badge_text_ms": "",
    "spare_parts": [
        {"name":"Coated Steel Cable","name_zh":"包胶钢丝绳","name_ms":"","qty":"Universal stock","qty_zh":"通用库","qty_ms":"","cycle":"18-24 months","cycle_zh":"18-24个月","cycle_ms":""},
        {"name":"Pulley w/ Bearing","name_zh":"滑轮（含轴承）","name_ms":"","qty":"Universal stock","qty_zh":"通用库","qty_ms":"","cycle":"24-36 months","cycle_zh":"24-36个月","cycle_ms":""},
        {"name":"Weight Pin","name_zh":"插片选择销","name_ms":"","qty":"Universal stock","qty_zh":"通用库","qty_ms":"","cycle":"12 months","cycle_zh":"12个月","cycle_ms":""},
        {"name":"Guide Rod Bushing","name_zh":"导轨塑料衬套","name_ms":"","qty":"Universal stock","qty_zh":"通用库","qty_ms":"","cycle":"12-18 months","cycle_zh":"12-18个月","cycle_ms":""},
        {"name":"Spherical Bearing","name_zh":"关节轴承","name_ms":"","qty":"Universal stock","qty_zh":"通用库","qty_ms":"","cycle":"24-36 months","cycle_zh":"24-36个月","cycle_ms":""},
        {"name":"Handle Foam Grip","name_zh":"手柄海绵套","name_ms":"","qty":"Universal stock","qty_zh":"通用库","qty_ms":"","cycle":"6-12 months","cycle_zh":"6-12个月","cycle_ms":""},
        {"name":"Seat/Back Pad","name_zh":"座垫/靠垫","name_ms":"","qty":"Universal stock","qty_zh":"通用库","qty_ms":"","cycle":"18-24 months","cycle_zh":"18-24个月","cycle_ms":""},
    ],
    "schedule": [
        {"interval":"Daily","interval_zh":"每天","interval_ms":"","action":"Wipe sweat from seat pad and handles","action_zh":"擦拭座垫和把手汗渍","action_ms":""},
        {"interval":"Weekly","interval_zh":"每周","interval_ms":"","action":"Check weight pin spring return, visually inspect steel cable","action_zh":"检查插片选择销弹簧回弹，目视检查钢丝绳","action_ms":""},
        {"interval":"Monthly","interval_zh":"每月","interval_ms":"","action":"Apply grease to weight stack guide rods","action_zh":"配重片导轨涂润滑脂","action_ms":""},
        {"interval":"Quarterly","interval_zh":"每季度","interval_ms":"","action":"Check pulleys and spherical bearings","action_zh":"检查滑轮和关节轴承","action_ms":""},
        {"interval":"Semi-annually","interval_zh":"每半年","interval_ms":"","action":"Tighten all bolts, full cable inspection","action_zh":"全机螺栓紧固，钢丝绳全面检查","action_ms":""},
    ],
    "durability_note": "Commercial-grade pin-loaded structure. Weight stack guide rods are hard-chrome plated, with wear life exceeding 500,000 motion cycles.",
    "durability_note_zh": "商用级插片式结构，配重片导轨经硬铬处理，耐磨寿命超过50万次动作循环。",
    "durability_note_ms": "",
},

"FS-003": {
    "badge": "full-kit",
    "badge_text": "Full spare parts kit shipped with equipment",
    "badge_text_zh": "全套备件已随货配送",
    "badge_text_ms": "",
    "spare_parts": [
        {"name":"Coated Steel Cable","name_zh":"包胶钢丝绳","name_ms":"","qty":"Universal stock","qty_zh":"通用库","qty_ms":"","cycle":"18-24 months","cycle_zh":"18-24个月","cycle_ms":""},
        {"name":"Pulley w/ Bearing","name_zh":"滑轮（含轴承）","name_ms":"","qty":"Universal stock","qty_zh":"通用库","qty_ms":"","cycle":"24-36 months","cycle_zh":"24-36个月","cycle_ms":""},
        {"name":"Weight Pin","name_zh":"插片选择销","name_ms":"","qty":"Universal stock","qty_zh":"通用库","qty_ms":"","cycle":"12 months","cycle_zh":"12个月","cycle_ms":""},
        {"name":"Guide Rod Bushing","name_zh":"导轨塑料衬套","name_ms":"","qty":"Universal stock","qty_zh":"通用库","qty_ms":"","cycle":"12-18 months","cycle_zh":"12-18个月","cycle_ms":""},
        {"name":"Spherical Bearing","name_zh":"关节轴承","name_ms":"","qty":"Universal stock","qty_zh":"通用库","qty_ms":"","cycle":"24-36 months","cycle_zh":"24-36个月","cycle_ms":""},
        {"name":"Handle Foam Grip","name_zh":"手柄海绵套","name_ms":"","qty":"Universal stock","qty_zh":"通用库","qty_ms":"","cycle":"6-12 months","cycle_zh":"6-12个月","cycle_ms":""},
        {"name":"Seat/Back Pad","name_zh":"座垫/靠垫","name_ms":"","qty":"Universal stock","qty_zh":"通用库","qty_ms":"","cycle":"18-24 months","cycle_zh":"18-24个月","cycle_ms":""},
    ],
    "schedule": [
        {"interval":"Daily","interval_zh":"每天","interval_ms":"","action":"Wipe sweat from seat pad and handles","action_zh":"擦拭座垫和把手汗渍","action_ms":""},
        {"interval":"Weekly","interval_zh":"每周","interval_ms":"","action":"Check weight pin and steel cable","action_zh":"检查选择销和钢丝绳","action_ms":""},
        {"interval":"Monthly","interval_zh":"每月","interval_ms":"","action":"Lubricate guide rods","action_zh":"导轨润滑","action_ms":""},
        {"interval":"Quarterly","interval_zh":"每季度","interval_ms":"","action":"Check pulleys and bearings","action_zh":"滑轮和轴承检查","action_ms":""},
        {"interval":"Semi-annually","interval_zh":"每半年","interval_ms":"","action":"Full bolt tightening inspection","action_zh":"全机紧固检查","action_ms":""},
    ],
    "durability_note": "Adjustable handle uses industrial-grade locking mechanism — no loosening after 100,000 adjustments. Cable routing uses large-radius design to reduce bending wear.",
    "durability_note_zh": "可调把手采用工业级锁紧机构，十万次调节无松动。钢丝绳走线采用大弧度设计，减少弯折磨损。",
    "durability_note_ms": "",
},

"FS-004": {
    "badge": "full-kit",
    "badge_text": "Full spare parts kit shipped with equipment",
    "badge_text_zh": "全套备件已随货配送",
    "badge_text_ms": "",
    "spare_parts": [
        {"name":"Coated Steel Cable","name_zh":"包胶钢丝绳","name_ms":"","qty":"Universal stock","qty_zh":"通用库","qty_ms":"","cycle":"18-24 months","cycle_zh":"18-24个月","cycle_ms":""},
        {"name":"Pulley w/ Bearing","name_zh":"滑轮（含轴承）","name_ms":"","qty":"Universal stock","qty_zh":"通用库","qty_ms":"","cycle":"24-36 months","cycle_zh":"24-36个月","cycle_ms":""},
        {"name":"Weight Pin","name_zh":"插片选择销","name_ms":"","qty":"Universal stock","qty_zh":"通用库","qty_ms":"","cycle":"12 months","cycle_zh":"12个月","cycle_ms":""},
        {"name":"Handle Foam Grip","name_zh":"手柄海绵套","name_ms":"","qty":"Universal stock","qty_zh":"通用库","qty_ms":"","cycle":"6-12 months","cycle_zh":"6-12个月","cycle_ms":""},
        {"name":"Elbow Pad","name_zh":"肘垫","name_ms":"","qty":"Universal stock","qty_zh":"通用库","qty_ms":"","cycle":"18-24 months","cycle_zh":"18-24个月","cycle_ms":""},
    ],
    "schedule": [
        {"interval":"Daily","interval_zh":"每天","interval_ms":"","action":"Wipe sweat from elbow pad and handles","action_zh":"擦拭肘垫和把手汗渍","action_ms":""},
        {"interval":"Weekly","interval_zh":"每周","interval_ms":"","action":"Check weight pin","action_zh":"检查选择销","action_ms":""},
        {"interval":"Monthly","interval_zh":"每月","interval_ms":"","action":"Lubricate guide rods","action_zh":"导轨润滑","action_ms":""},
        {"interval":"Quarterly","interval_zh":"每季度","interval_ms":"","action":"Check pulleys and bearings","action_zh":"滑轮和轴承检查","action_ms":""},
        {"interval":"Semi-annually","interval_zh":"每半年","interval_ms":"","action":"Tighten all bolts","action_zh":"全机紧固","action_ms":""},
    ],
    "durability_note": "Single-joint isolation machine with short transmission path and simple force dynamics — one of the lowest failure-rate types among all pin-loaded equipment.",
    "durability_note_zh": "单关节运动器械，传动路径短、受力简单，是所有固定器械中故障率最低的类型之一。",
    "durability_note_ms": "",
},

"FS-005": {
    "badge": "full-kit",
    "badge_text": "Full spare parts kit shipped with equipment",
    "badge_text_zh": "全套备件已随货配送",
    "badge_text_ms": "",
    "spare_parts": [
        {"name":"Coated Steel Cable","name_zh":"包胶钢丝绳","name_ms":"","qty":"Universal stock","qty_zh":"通用库","qty_ms":"","cycle":"18-24 months","cycle_zh":"18-24个月","cycle_ms":""},
        {"name":"Pulley w/ Bearing","name_zh":"滑轮（含轴承）","name_ms":"","qty":"Universal stock","qty_zh":"通用库","qty_ms":"","cycle":"24-36 months","cycle_zh":"24-36个月","cycle_ms":""},
        {"name":"Weight Pin","name_zh":"插片选择销","name_ms":"","qty":"Universal stock","qty_zh":"通用库","qty_ms":"","cycle":"12 months","cycle_zh":"12个月","cycle_ms":""},
        {"name":"Quick-adjust Spring Pin","name_zh":"快调键弹簧+锁销","name_ms":"","qty":"3 sets from universal stock","qty_zh":"通用库备3套","qty_ms":"","cycle":"12 months","cycle_zh":"12个月","cycle_ms":""},
        {"name":"PU Roller Pad","name_zh":"PU滚轮垫","name_ms":"","qty":"Universal stock","qty_zh":"通用库","qty_ms":"","cycle":"12-18 months","cycle_zh":"12-18个月","cycle_ms":""},
        {"name":"Prone Pad","name_zh":"趴卧垫","name_ms":"","qty":"Universal stock","qty_zh":"通用库","qty_ms":"","cycle":"18-24 months","cycle_zh":"18-24个月","cycle_ms":""},
    ],
    "schedule": [
        {"interval":"Daily","interval_zh":"每天","interval_ms":"","action":"Wipe sweat from prone pad","action_zh":"擦拭趴卧垫汗渍","action_ms":""},
        {"interval":"Weekly","interval_zh":"每周","interval_ms":"","action":"Check weight pin and quick-adjust lock","action_zh":"检查选择销和快调键锁定","action_ms":""},
        {"interval":"Monthly","interval_zh":"每月","interval_ms":"","action":"Lubricate guide rods, check PU roller pad wear","action_zh":"导轨润滑，检查PU滚轮垫磨损","action_ms":""},
        {"interval":"Quarterly","interval_zh":"每季度","interval_ms":"","action":"Check pulleys and bearings","action_zh":"滑轮和轴承检查","action_ms":""},
        {"interval":"Semi-annually","interval_zh":"每半年","interval_ms":"","action":"Tighten all bolts","action_zh":"全机紧固","action_ms":""},
    ],
    "durability_note": "Quick-adjust key uses spring lock pin mechanism. Ample replacement parts stocked — swap takes 30 seconds when needed.",
    "durability_note_zh": "快调键采用弹簧锁销结构，已备充足替换件，随坏随换30秒搞定。",
    "durability_note_ms": "",
},

"FS-006": {
    "badge": "full-kit",
    "badge_text": "Full spare parts kit shipped with equipment",
    "badge_text_zh": "全套备件已随货配送",
    "badge_text_ms": "",
    "spare_parts": [
        {"name":"Coated Steel Cable","name_zh":"包胶钢丝绳","name_ms":"","qty":"Universal stock","qty_zh":"通用库","qty_ms":"","cycle":"18-24 months","cycle_zh":"18-24个月","cycle_ms":""},
        {"name":"Pulley w/ Bearing","name_zh":"滑轮（含轴承）","name_ms":"","qty":"Universal stock","qty_zh":"通用库","qty_ms":"","cycle":"24-36 months","cycle_zh":"24-36个月","cycle_ms":""},
        {"name":"Weight Pin","name_zh":"插片选择销","name_ms":"","qty":"Universal stock","qty_zh":"通用库","qty_ms":"","cycle":"12 months","cycle_zh":"12个月","cycle_ms":""},
        {"name":"Quick-adjust Spring Pin","name_zh":"快调键弹簧+锁销","name_ms":"","qty":"Universal stock","qty_zh":"通用库","qty_ms":"","cycle":"12 months","cycle_zh":"12个月","cycle_ms":""},
        {"name":"PU Roller Pad","name_zh":"PU滚轮垫","name_ms":"","qty":"Universal stock","qty_zh":"通用库","qty_ms":"","cycle":"12-18 months","cycle_zh":"12-18个月","cycle_ms":""},
        {"name":"Seat/Back Pad","name_zh":"座垫/靠垫","name_ms":"","qty":"Universal stock","qty_zh":"通用库","qty_ms":"","cycle":"18-24 months","cycle_zh":"18-24个月","cycle_ms":""},
    ],
    "schedule": [
        {"interval":"Daily","interval_zh":"每天","interval_ms":"","action":"Wipe sweat from seat pad","action_zh":"擦拭座垫汗渍","action_ms":""},
        {"interval":"Weekly","interval_zh":"每周","interval_ms":"","action":"Check weight pin and quick-adjust key","action_zh":"检查选择销和快调键","action_ms":""},
        {"interval":"Monthly","interval_zh":"每月","interval_ms":"","action":"Lubricate guide rods","action_zh":"导轨润滑","action_ms":""},
        {"interval":"Quarterly","interval_zh":"每季度","interval_ms":"","action":"Check pulleys","action_zh":"滑轮检查","action_ms":""},
        {"interval":"Semi-annually","interval_zh":"每半年","interval_ms":"","action":"Tighten all bolts","action_zh":"全机紧固","action_ms":""},
    ],
    "durability_note": "Shares the same spec quick-adjust key parts with prone leg curl — mutual redundancy backup.",
    "durability_note_zh": "与俯卧曲腿共用同规格快调键备件，互为冗余保障。",
    "durability_note_ms": "",
},

"FS-007": {
    "badge": "full-kit",
    "badge_text": "Full spare parts kit shipped with equipment",
    "badge_text_zh": "全套备件已随货配送",
    "badge_text_ms": "",
    "spare_parts": [
        {"name":"Coated Steel Cable","name_zh":"包胶钢丝绳","name_ms":"","qty":"Universal stock","qty_zh":"通用库","qty_ms":"","cycle":"18-24 months","cycle_zh":"18-24个月","cycle_ms":""},
        {"name":"Pulley w/ Bearing","name_zh":"滑轮（含轴承）","name_ms":"","qty":"Universal stock","qty_zh":"通用库","qty_ms":"","cycle":"24-36 months","cycle_zh":"24-36个月","cycle_ms":""},
        {"name":"Weight Pin","name_zh":"插片选择销","name_ms":"","qty":"Universal stock","qty_zh":"通用库","qty_ms":"","cycle":"12 months","cycle_zh":"12个月","cycle_ms":""},
        {"name":"Spherical Bearing","name_zh":"关节轴承","name_ms":"","qty":"Universal stock","qty_zh":"通用库","qty_ms":"","cycle":"24-36 months","cycle_zh":"24-36个月","cycle_ms":""},
        {"name":"Leg Pad","name_zh":"腿部挡垫","name_ms":"","qty":"Universal stock","qty_zh":"通用库","qty_ms":"","cycle":"18-24 months","cycle_zh":"18-24个月","cycle_ms":""},
        {"name":"Seat/Back Pad","name_zh":"座垫/靠垫","name_ms":"","qty":"Universal stock","qty_zh":"通用库","qty_ms":"","cycle":"18-24 months","cycle_zh":"18-24个月","cycle_ms":""},
    ],
    "schedule": [
        {"interval":"Daily","interval_zh":"每天","interval_ms":"","action":"Wipe sweat from all contact surfaces","action_zh":"擦拭所有接触面汗渍","action_ms":""},
        {"interval":"Weekly","interval_zh":"每周","interval_ms":"","action":"Check weight pin","action_zh":"检查选择销","action_ms":""},
        {"interval":"Monthly","interval_zh":"每月","interval_ms":"","action":"Lubricate guide rods, check inner/outer switch mechanism","action_zh":"导轨润滑，内外侧切换机构检查","action_ms":""},
        {"interval":"Quarterly","interval_zh":"每季度","interval_ms":"","action":"Grease spherical bearings","action_zh":"关节轴承注脂","action_ms":""},
        {"interval":"Semi-annually","interval_zh":"每半年","interval_ms":"","action":"Tighten all bolts","action_zh":"全机紧固","action_ms":""},
    ],
    "durability_note": "Single machine switches between inner/outer thigh with adjustable backrest. Switching mechanism uses rack-and-pinion lock — no loosening after 100,000 switches.",
    "durability_note_zh": "内外侧一机切换设计，靠背角度可调，调节机构采用齿条锁定，10万次切换无松动。",
    "durability_note_ms": "",
},

"FS-008": {
    "badge": "full-kit",
    "badge_text": "Full spare parts kit shipped with equipment",
    "badge_text_zh": "全套备件已随货配送",
    "badge_text_ms": "",
    "spare_parts": [
        {"name":"Coated Steel Cable","name_zh":"包胶钢丝绳","name_ms":"","qty":"Universal stock (this unit uses longer cable, ~4-5m)","qty_zh":"通用库（此机用绳较长，约4-5m）","qty_ms":"","cycle":"18-24 months","cycle_zh":"18-24个月","cycle_ms":""},
        {"name":"Pulley w/ Bearing","name_zh":"滑轮（含轴承）","name_ms":"","qty":"Universal stock (this unit uses 6-8 pulleys)","qty_zh":"通用库（此机滑轮较多，6-8个）","qty_ms":"","cycle":"24-36 months","cycle_zh":"24-36个月","cycle_ms":""},
        {"name":"Weight Pin","name_zh":"插片选择销","name_ms":"","qty":"Universal stock","qty_zh":"通用库","qty_ms":"","cycle":"12 months","cycle_zh":"12个月","cycle_ms":""},
        {"name":"Height Adjust Ratchet Pin","name_zh":"高度调节棘爪/弹簧销","name_ms":"","qty":"2 pcs","qty_zh":"2个","qty_ms":"","cycle":"12-18 months","cycle_zh":"12-18个月","cycle_ms":""},
        {"name":"Handle Attachments","name_zh":"手柄/配件挂钩","name_ms":"","qty":"1 set","qty_zh":"1套","qty_ms":"","cycle":"Replace when worn","cycle_zh":"磨损即换","cycle_ms":""},
        {"name":"Seat Pad","name_zh":"座垫","name_ms":"","qty":"Universal stock","qty_zh":"通用库","qty_ms":"","cycle":"18-24 months","cycle_zh":"18-24个月","cycle_ms":""},
    ],
    "schedule": [
        {"interval":"Daily","interval_zh":"每天","interval_ms":"","action":"Wipe sweat from seat pad","action_zh":"擦拭座垫汗渍","action_ms":""},
        {"interval":"Weekly","interval_zh":"每周","interval_ms":"","action":"Check weight pin and height adjustment lock","action_zh":"检查选择销和高度调节锁定","action_ms":""},
        {"interval":"Monthly","interval_zh":"每月","interval_ms":"","action":"Lubricate guide rods, inspect cable (longest routing — focus on bend points)","action_zh":"导轨润滑，检查钢丝绳（此机走线最长，重点检查弯折处）","action_ms":""},
        {"interval":"Quarterly","interval_zh":"每季度","interval_ms":"","action":"Inspect all pulleys one by one","action_zh":"所有滑轮逐一检查","action_ms":""},
        {"interval":"Semi-annually","interval_zh":"每半年","interval_ms":"","action":"Tighten all bolts","action_zh":"全机紧固","action_ms":""},
    ],
    "durability_note": "Stepless hi-lo pulley adjustment — the most versatile single piece of equipment. Cable routing is long but uses large-radius pulley groups, minimizing bending stress.",
    "durability_note_zh": "高低滑轮无极调节，功能覆盖面最广的单台器械。钢丝绳走线虽长但采用大弧度滑轮组，弯折应力小。",
    "durability_note_ms": "",
},

"FS-009": {
    "badge": "full-kit",
    "badge_text": "Full spare parts kit shipped with equipment",
    "badge_text_zh": "全套备件已随货配送",
    "badge_text_ms": "",
    "spare_parts": [
        {"name":"Coated Steel Cable","name_zh":"包胶钢丝绳","name_ms":"","qty":"Universal stock","qty_zh":"通用库","qty_ms":"","cycle":"18-24 months","cycle_zh":"18-24个月","cycle_ms":""},
        {"name":"Pulley w/ Bearing","name_zh":"滑轮（含轴承）","name_ms":"","qty":"Universal stock","qty_zh":"通用库","qty_ms":"","cycle":"24-36 months","cycle_zh":"24-36个月","cycle_ms":""},
        {"name":"Weight Pin","name_zh":"插片选择销","name_ms":"","qty":"Universal stock","qty_zh":"通用库","qty_ms":"","cycle":"12 months","cycle_zh":"12个月","cycle_ms":""},
        {"name":"Spherical Bearing","name_zh":"关节轴承","name_ms":"","qty":"Universal stock","qty_zh":"通用库","qty_ms":"","cycle":"24-36 months","cycle_zh":"24-36个月","cycle_ms":""},
        {"name":"Handle Foam Grip","name_zh":"手柄海绵套","name_ms":"","qty":"Universal stock","qty_zh":"通用库","qty_ms":"","cycle":"6-12 months","cycle_zh":"6-12个月","cycle_ms":""},
    ],
    "schedule": [
        {"interval":"Daily","interval_zh":"每天","interval_ms":"","action":"Wipe sweat from handles","action_zh":"擦拭把手汗渍","action_ms":""},
        {"interval":"Weekly","interval_zh":"每周","interval_ms":"","action":"Check weight pin","action_zh":"检查选择销","action_ms":""},
        {"interval":"Monthly","interval_zh":"每月","interval_ms":"","action":"Lubricate guide rods","action_zh":"导轨润滑","action_ms":""},
        {"interval":"Quarterly","interval_zh":"每季度","interval_ms":"","action":"Check pulleys and spherical bearings","action_zh":"滑轮和关节轴承检查","action_ms":""},
        {"interval":"Semi-annually","interval_zh":"每半年","interval_ms":"","action":"Tighten all bolts","action_zh":"全机紧固","action_ms":""},
    ],
    "durability_note": "Gen 2 upgrade, 268kg net weight — extremely stable. Dual weight stacks operate independently without interference.",
    "durability_note_zh": "二代升级款，净重268kg，整机稳定性极强。双配重塔独立运行互不干扰。",
    "durability_note_ms": "",
},

"FS-010": {
    "badge": "full-kit",
    "badge_text": "Full spare parts kit shipped with equipment",
    "badge_text_zh": "全套备件已随货配送",
    "badge_text_ms": "",
    "spare_parts": [
        {"name":"Coated Steel Cable","name_zh":"包胶钢丝绳","name_ms":"","qty":"Universal stock","qty_zh":"通用库","qty_ms":"","cycle":"18-24 months","cycle_zh":"18-24个月","cycle_ms":""},
        {"name":"Pulley w/ Bearing","name_zh":"滑轮（含轴承）","name_ms":"","qty":"Universal stock","qty_zh":"通用库","qty_ms":"","cycle":"24-36 months","cycle_zh":"24-36个月","cycle_ms":""},
        {"name":"Weight Pin","name_zh":"插片选择销","name_ms":"","qty":"Universal stock","qty_zh":"通用库","qty_ms":"","cycle":"12 months","cycle_zh":"12个月","cycle_ms":""},
        {"name":"Arm Pad","name_zh":"臂垫","name_ms":"","qty":"Universal stock","qty_zh":"通用库","qty_ms":"","cycle":"18-24 months","cycle_zh":"18-24个月","cycle_ms":""},
    ],
    "schedule": [
        {"interval":"Daily","interval_zh":"每天","interval_ms":"","action":"Wipe sweat from arm pads","action_zh":"擦拭臂垫汗渍","action_ms":""},
        {"interval":"Weekly","interval_zh":"每周","interval_ms":"","action":"Check weight pin","action_zh":"检查选择销","action_ms":""},
        {"interval":"Monthly","interval_zh":"每月","interval_ms":"","action":"Lubricate guide rods","action_zh":"导轨润滑","action_ms":""},
        {"interval":"Quarterly","interval_zh":"每季度","interval_ms":"","action":"Check pulleys","action_zh":"滑轮检查","action_ms":""},
        {"interval":"Semi-annually","interval_zh":"每半年","interval_ms":"","action":"Tighten all bolts","action_zh":"全机紧固","action_ms":""},
    ],
    "durability_note": "Single-joint isolation machine with the shortest transmission path and simplest structure — extremely low failure rate.",
    "durability_note_zh": "单关节孤立动作器械，传动路径最短，结构最简单，故障率极低。",
    "durability_note_ms": "",
},

"FS-011": {
    "badge": "full-kit",
    "badge_text": "Full spare parts kit shipped with equipment",
    "badge_text_zh": "全套备件已随货配送",
    "badge_text_ms": "",
    "spare_parts": [
        {"name":"Coated Steel Cable","name_zh":"包胶钢丝绳","name_ms":"","qty":"Universal stock (dual arms, 1 cable each)","qty_zh":"通用库（双臂各1根）","qty_ms":"","cycle":"18-24 months","cycle_zh":"18-24个月","cycle_ms":""},
        {"name":"Pulley w/ Bearing","name_zh":"滑轮（含轴承）","name_ms":"","qty":"Universal stock (most pulleys of all units)","qty_zh":"通用库（此机滑轮较多）","qty_ms":"","cycle":"24-36 months","cycle_zh":"24-36个月","cycle_ms":""},
        {"name":"Weight Pin","name_zh":"插片选择销","name_ms":"","qty":"Universal stock","qty_zh":"通用库","qty_ms":"","cycle":"12 months","cycle_zh":"12个月","cycle_ms":""},
        {"name":"Spherical Bearing","name_zh":"关节轴承","name_ms":"","qty":"Universal stock","qty_zh":"通用库","qty_ms":"","cycle":"24-36 months","cycle_zh":"24-36个月","cycle_ms":""},
        {"name":"Handle Foam Grip","name_zh":"手柄海绵套","name_ms":"","qty":"Universal stock","qty_zh":"通用库","qty_ms":"","cycle":"6-12 months","cycle_zh":"6-12个月","cycle_ms":""},
        {"name":"Thigh Hold-down Pad","name_zh":"腿部固定垫","name_ms":"","qty":"Universal stock","qty_zh":"通用库","qty_ms":"","cycle":"18-24 months","cycle_zh":"18-24个月","cycle_ms":""},
    ],
    "schedule": [
        {"interval":"Daily","interval_zh":"每天","interval_ms":"","action":"Wipe sweat from seat and thigh pads","action_zh":"擦拭座垫和腿垫汗渍","action_ms":""},
        {"interval":"Weekly","interval_zh":"每周","interval_ms":"","action":"Check weight pin and steel cable","action_zh":"检查选择销和钢丝绳","action_ms":""},
        {"interval":"Monthly","interval_zh":"每月","interval_ms":"","action":"Lubricate guide rods","action_zh":"导轨润滑","action_ms":""},
        {"interval":"Quarterly","interval_zh":"每季度","interval_ms":"","action":"Inspect all pulleys one by one (highest pulley count)","action_zh":"全部滑轮逐一检查（此机滑轮数量最多）","action_ms":""},
        {"interval":"Semi-annually","interval_zh":"每半年","interval_ms":"","action":"Tighten all bolts","action_zh":"全机紧固","action_ms":""},
    ],
    "durability_note": "Diverging independent arm design with separate left/right weight stacks. 2520mm tall with extra-thick square tube main frame — outstanding stability.",
    "durability_note_zh": "分动独立臂设计，左右配重塔独立运行。整机高度2520mm，采用加厚方管主架体，稳定性出色。",
    "durability_note_ms": "",
},

"FS-012": {
    "badge": "full-kit",
    "badge_text": "Full spare parts kit shipped with equipment",
    "badge_text_zh": "全套备件已随货配送",
    "badge_text_ms": "",
    "spare_parts": [
        {"name":"Coated Steel Cable","name_zh":"包胶钢丝绳","name_ms":"","qty":"Universal stock","qty_zh":"通用库","qty_ms":"","cycle":"18-24 months","cycle_zh":"18-24个月","cycle_ms":""},
        {"name":"Pulley w/ Bearing","name_zh":"滑轮（含轴承）","name_ms":"","qty":"Universal stock","qty_zh":"通用库","qty_ms":"","cycle":"24-36 months","cycle_zh":"24-36个月","cycle_ms":""},
        {"name":"Weight Pin","name_zh":"插片选择销","name_ms":"","qty":"Universal stock","qty_zh":"通用库","qty_ms":"","cycle":"12 months","cycle_zh":"12个月","cycle_ms":""},
        {"name":"Handle Foam Grip","name_zh":"手柄海绵套","name_ms":"","qty":"Universal stock","qty_zh":"通用库","qty_ms":"","cycle":"6-12 months","cycle_zh":"6-12个月","cycle_ms":""},
        {"name":"Seat/Back Pad","name_zh":"座垫/靠垫","name_ms":"","qty":"Universal stock","qty_zh":"通用库","qty_ms":"","cycle":"18-24 months","cycle_zh":"18-24个月","cycle_ms":""},
    ],
    "schedule": [
        {"interval":"Daily","interval_zh":"每天","interval_ms":"","action":"Wipe sweat from seat pad","action_zh":"擦拭座垫汗渍","action_ms":""},
        {"interval":"Weekly","interval_zh":"每周","interval_ms":"","action":"Check weight pin","action_zh":"检查选择销","action_ms":""},
        {"interval":"Monthly","interval_zh":"每月","interval_ms":"","action":"Lubricate guide rods","action_zh":"导轨润滑","action_ms":""},
        {"interval":"Quarterly","interval_zh":"每季度","interval_ms":"","action":"Check pulleys and bearings","action_zh":"滑轮和轴承检查","action_ms":""},
        {"interval":"Semi-annually","interval_zh":"每半年","interval_ms":"","action":"Tighten all bolts","action_zh":"全机紧固","action_ms":""},
    ],
    "durability_note": "Shoulder press machines have vertical upward force direction — minimal guide rod wear, longest guide rod lifespan among all pin-loaded equipment.",
    "durability_note_zh": "推肩类器械受力方向为垂直向上，配重片导轨磨损最小，是所有固定器械中导轨寿命最长的类型。",
    "durability_note_ms": "",
},

"FS-013": {
    "badge": "full-kit",
    "badge_text": "Full spare parts kit shipped with equipment",
    "badge_text_zh": "全套备件已随货配送",
    "badge_text_ms": "",
    "spare_parts": [
        {"name":"Coated Steel Cable","name_zh":"包胶钢丝绳","name_ms":"","qty":"Universal stock","qty_zh":"通用库","qty_ms":"","cycle":"18-24 months","cycle_zh":"18-24个月","cycle_ms":""},
        {"name":"Pulley w/ Bearing","name_zh":"滑轮（含轴承）","name_ms":"","qty":"Universal stock","qty_zh":"通用库","qty_ms":"","cycle":"24-36 months","cycle_zh":"24-36个月","cycle_ms":""},
        {"name":"Weight Pin","name_zh":"插片选择销","name_ms":"","qty":"Universal stock","qty_zh":"通用库","qty_ms":"","cycle":"12 months","cycle_zh":"12个月","cycle_ms":""},
        {"name":"Spherical Bearing","name_zh":"关节轴承","name_ms":"","qty":"Universal stock","qty_zh":"通用库","qty_ms":"","cycle":"24-36 months","cycle_zh":"24-36个月","cycle_ms":""},
        {"name":"Handle Foam Grip","name_zh":"手柄海绵套","name_ms":"","qty":"Universal stock","qty_zh":"通用库","qty_ms":"","cycle":"6-12 months","cycle_zh":"6-12个月","cycle_ms":""},
        {"name":"Chest Pad","name_zh":"胸垫","name_ms":"","qty":"Universal stock","qty_zh":"通用库","qty_ms":"","cycle":"18-24 months","cycle_zh":"18-24个月","cycle_ms":""},
    ],
    "schedule": [
        {"interval":"Daily","interval_zh":"每天","interval_ms":"","action":"Wipe sweat from chest pad","action_zh":"擦拭胸垫汗渍","action_ms":""},
        {"interval":"Weekly","interval_zh":"每周","interval_ms":"","action":"Check weight pin and steel cable","action_zh":"检查选择销和钢丝绳","action_ms":""},
        {"interval":"Monthly","interval_zh":"每月","interval_ms":"","action":"Lubricate guide rods","action_zh":"导轨润滑","action_ms":""},
        {"interval":"Quarterly","interval_zh":"每季度","interval_ms":"","action":"Check pulleys and spherical bearings","action_zh":"滑轮和关节轴承检查","action_ms":""},
        {"interval":"Semi-annually","interval_zh":"每半年","interval_ms":"","action":"Tighten all bolts","action_zh":"全机紧固","action_ms":""},
    ],
    "durability_note": "Diverging independent arms correct left/right strength imbalances. Dual weight stacks operate independently — one side's failure doesn't affect the other.",
    "durability_note_zh": "分动独立臂设计纠正左右力量不平衡，双配重塔独立运行，单侧故障不影响另一侧使用。",
    "durability_note_ms": "",
},

"FS-014": {
    "badge": "full-kit",
    "badge_text": "Full spare parts kit shipped with equipment",
    "badge_text_zh": "全套备件已随货配送",
    "badge_text_ms": "",
    "spare_parts": [
        {"name":"Coated Steel Cable","name_zh":"包胶钢丝绳","name_ms":"","qty":"Universal stock","qty_zh":"通用库","qty_ms":"","cycle":"18-24 months","cycle_zh":"18-24个月","cycle_ms":""},
        {"name":"Pulley w/ Bearing","name_zh":"滑轮（含轴承）","name_ms":"","qty":"Universal stock","qty_zh":"通用库","qty_ms":"","cycle":"24-36 months","cycle_zh":"24-36个月","cycle_ms":""},
        {"name":"Weight Pin","name_zh":"插片选择销","name_ms":"","qty":"Universal stock","qty_zh":"通用库","qty_ms":"","cycle":"12 months","cycle_zh":"12个月","cycle_ms":""},
        {"name":"Spherical Bearing","name_zh":"关节轴承","name_ms":"","qty":"Universal stock","qty_zh":"通用库","qty_ms":"","cycle":"24-36 months","cycle_zh":"24-36个月","cycle_ms":""},
        {"name":"Handle Foam Grip","name_zh":"手柄海绵套","name_ms":"","qty":"Universal stock","qty_zh":"通用库","qty_ms":"","cycle":"6-12 months","cycle_zh":"6-12个月","cycle_ms":""},
        {"name":"Seat/Back Pad","name_zh":"座垫/靠垫","name_ms":"","qty":"Universal stock","qty_zh":"通用库","qty_ms":"","cycle":"18-24 months","cycle_zh":"18-24个月","cycle_ms":""},
    ],
    "schedule": [
        {"interval":"Daily","interval_zh":"每天","interval_ms":"","action":"Wipe sweat from seat pad","action_zh":"擦拭座垫汗渍","action_ms":""},
        {"interval":"Weekly","interval_zh":"每周","interval_ms":"","action":"Check weight pin","action_zh":"检查选择销","action_ms":""},
        {"interval":"Monthly","interval_zh":"每月","interval_ms":"","action":"Lubricate guide rods","action_zh":"导轨润滑","action_ms":""},
        {"interval":"Quarterly","interval_zh":"每季度","interval_ms":"","action":"Check pulleys and bearings","action_zh":"滑轮和轴承检查","action_ms":""},
        {"interval":"Semi-annually","interval_zh":"每半年","interval_ms":"","action":"Tighten all bolts","action_zh":"全机紧固","action_ms":""},
    ],
    "durability_note": "Super-incline angle precisely locked. Angle adjustment rack is carburized to HRC58+ hardness — no wear after tens of thousands of adjustments.",
    "durability_note_zh": "超上斜角度精准锁定，角度调节齿条经渗碳处理，硬度HRC58以上，数万次调节无磨损。",
    "durability_note_ms": "",
},

"FS-015": {
    "badge": "full-kit",
    "badge_text": "Full spare parts kit shipped with equipment",
    "badge_text_zh": "全套备件已随货配送",
    "badge_text_ms": "",
    "spare_parts": [
        {"name":"Coated Steel Cable","name_zh":"包胶钢丝绳","name_ms":"","qty":"Universal stock","qty_zh":"通用库","qty_ms":"","cycle":"18-24 months","cycle_zh":"18-24个月","cycle_ms":""},
        {"name":"Pulley w/ Bearing","name_zh":"滑轮（含轴承）","name_ms":"","qty":"Universal stock","qty_zh":"通用库","qty_ms":"","cycle":"24-36 months","cycle_zh":"24-36个月","cycle_ms":""},
        {"name":"Weight Pin","name_zh":"插片选择销","name_ms":"","qty":"Universal stock","qty_zh":"通用库","qty_ms":"","cycle":"12 months","cycle_zh":"12个月","cycle_ms":""},
        {"name":"Spherical Bearing","name_zh":"关节轴承","name_ms":"","qty":"Universal stock","qty_zh":"通用库","qty_ms":"","cycle":"24-36 months","cycle_zh":"24-36个月","cycle_ms":""},
        {"name":"Handle Foam Grip","name_zh":"手柄海绵套","name_ms":"","qty":"Universal stock","qty_zh":"通用库","qty_ms":"","cycle":"6-12 months","cycle_zh":"6-12个月","cycle_ms":""},
        {"name":"Seat/Back Pad","name_zh":"座垫/靠垫","name_ms":"","qty":"Universal stock","qty_zh":"通用库","qty_ms":"","cycle":"18-24 months","cycle_zh":"18-24个月","cycle_ms":""},
    ],
    "schedule": [
        {"interval":"Daily","interval_zh":"每天","interval_ms":"","action":"Wipe sweat from seat pad","action_zh":"擦拭座垫汗渍","action_ms":""},
        {"interval":"Weekly","interval_zh":"每周","interval_ms":"","action":"Check weight pin","action_zh":"检查选择销","action_ms":""},
        {"interval":"Monthly","interval_zh":"每月","interval_ms":"","action":"Lubricate guide rods","action_zh":"导轨润滑","action_ms":""},
        {"interval":"Quarterly","interval_zh":"每季度","interval_ms":"","action":"Check pulleys and bearings","action_zh":"滑轮和轴承检查","action_ms":""},
        {"interval":"Semi-annually","interval_zh":"每半年","interval_ms":"","action":"Tighten all bolts","action_zh":"全机紧固","action_ms":""},
    ],
    "durability_note": "Wide-angle movement trajectory puts higher lateral forces on spherical bearings. Extra spherical bearings have been stocked in the universal parts inventory for this type.",
    "durability_note_zh": "阔角度运动轨迹设计，关节轴承承受侧向力较大，已在通用库中为此类器械额外备足关节轴承。",
    "durability_note_ms": "",
},

"FS-016": {
    "badge": "full-kit",
    "badge_text": "Full spare parts kit shipped with equipment",
    "badge_text_zh": "全套备件已随货配送",
    "badge_text_ms": "",
    "spare_parts": [
        {"name":"Coated Steel Cable","name_zh":"包胶钢丝绳","name_ms":"","qty":"Universal stock","qty_zh":"通用库","qty_ms":"","cycle":"18-24 months","cycle_zh":"18-24个月","cycle_ms":""},
        {"name":"Pulley w/ Bearing","name_zh":"滑轮（含轴承）","name_ms":"","qty":"Universal stock","qty_zh":"通用库","qty_ms":"","cycle":"24-36 months","cycle_zh":"24-36个月","cycle_ms":""},
        {"name":"Weight Pin","name_zh":"插片选择销","name_ms":"","qty":"Universal stock","qty_zh":"通用库","qty_ms":"","cycle":"12 months","cycle_zh":"12个月","cycle_ms":""},
        {"name":"Handle Foam Grip","name_zh":"手柄海绵套","name_ms":"","qty":"Universal stock","qty_zh":"通用库","qty_ms":"","cycle":"6-12 months","cycle_zh":"6-12个月","cycle_ms":""},
        {"name":"Seat Pad","name_zh":"座垫","name_ms":"","qty":"Universal stock","qty_zh":"通用库","qty_ms":"","cycle":"18-24 months","cycle_zh":"18-24个月","cycle_ms":""},
    ],
    "schedule": [
        {"interval":"Daily","interval_zh":"每天","interval_ms":"","action":"Wipe sweat from seat pad and handles","action_zh":"擦拭座垫和把手汗渍","action_ms":""},
        {"interval":"Weekly","interval_zh":"每周","interval_ms":"","action":"Check weight pin","action_zh":"检查选择销","action_ms":""},
        {"interval":"Monthly","interval_zh":"每月","interval_ms":"","action":"Lubricate guide rods","action_zh":"导轨润滑","action_ms":""},
        {"interval":"Quarterly","interval_zh":"每季度","interval_ms":"","action":"Check pulleys","action_zh":"滑轮检查","action_ms":""},
        {"interval":"Semi-annually","interval_zh":"每半年","interval_ms":"","action":"Tighten all bolts","action_zh":"全机紧固","action_ms":""},
    ],
    "durability_note": "Tricep dip has short range of motion and light weight loads. Cable and pulleys experience the least stress — one of the most durable pin-loaded machines in the gym.",
    "durability_note_zh": "臂下压动作行程短、配重轻，钢丝绳和滑轮受力最小，全场固定器械中最耐用的几台之一。",
    "durability_note_ms": "",
},

"FS-017": {
    "badge": "full-kit",
    "badge_text": "Full spare parts kit shipped with equipment",
    "badge_text_zh": "全套备件已随货配送",
    "badge_text_ms": "",
    "spare_parts": [
        {"name":"Coated Steel Cable","name_zh":"包胶钢丝绳","name_ms":"","qty":"Universal stock","qty_zh":"通用库","qty_ms":"","cycle":"18-24 months","cycle_zh":"18-24个月","cycle_ms":""},
        {"name":"Pulley w/ Bearing","name_zh":"滑轮（含轴承）","name_ms":"","qty":"Universal stock","qty_zh":"通用库","qty_ms":"","cycle":"24-36 months","cycle_zh":"24-36个月","cycle_ms":""},
        {"name":"Weight Pin","name_zh":"插片选择销","name_ms":"","qty":"Universal stock","qty_zh":"通用库","qty_ms":"","cycle":"12 months","cycle_zh":"12个月","cycle_ms":""},
        {"name":"Spherical Bearing","name_zh":"关节轴承","name_ms":"","qty":"Universal stock","qty_zh":"通用库","qty_ms":"","cycle":"24-36 months","cycle_zh":"24-36个月","cycle_ms":""},
        {"name":"Handle Foam Grip","name_zh":"手柄海绵套","name_ms":"","qty":"Universal stock","qty_zh":"通用库","qty_ms":"","cycle":"6-12 months","cycle_zh":"6-12个月","cycle_ms":""},
        {"name":"Seat/Back Pad","name_zh":"座垫/靠垫","name_ms":"","qty":"Universal stock","qty_zh":"通用库","qty_ms":"","cycle":"18-24 months","cycle_zh":"18-24个月","cycle_ms":""},
    ],
    "schedule": [
        {"interval":"Daily","interval_zh":"每天","interval_ms":"","action":"Wipe sweat from seat pad","action_zh":"擦拭座垫汗渍","action_ms":""},
        {"interval":"Weekly","interval_zh":"每周","interval_ms":"","action":"Check weight pin","action_zh":"检查选择销","action_ms":""},
        {"interval":"Monthly","interval_zh":"每月","interval_ms":"","action":"Lubricate guide rods","action_zh":"导轨润滑","action_ms":""},
        {"interval":"Quarterly","interval_zh":"每季度","interval_ms":"","action":"Check pulleys and bearings","action_zh":"滑轮和轴承检查","action_ms":""},
        {"interval":"Semi-annually","interval_zh":"每半年","interval_ms":"","action":"Tighten all bolts","action_zh":"全机紧固","action_ms":""},
    ],
    "durability_note": "Fixed decline angle design — no angle adjustment mechanism means fewer structural parts and higher reliability.",
    "durability_note_zh": "下斜角度固定设计，无角度调节机构，结构件更少，可靠性更高。",
    "durability_note_ms": "",
},

"FS-018": {
    "badge": "full-kit",
    "badge_text": "Full spare parts kit shipped with equipment",
    "badge_text_zh": "全套备件已随货配送",
    "badge_text_ms": "",
    "spare_parts": [
        {"name":"Coated Steel Cable","name_zh":"包胶钢丝绳","name_ms":"","qty":"Universal stock","qty_zh":"通用库","qty_ms":"","cycle":"18-24 months","cycle_zh":"18-24个月","cycle_ms":""},
        {"name":"Pulley w/ Bearing","name_zh":"滑轮（含轴承）","name_ms":"","qty":"Universal stock","qty_zh":"通用库","qty_ms":"","cycle":"24-36 months","cycle_zh":"24-36个月","cycle_ms":""},
        {"name":"Weight Pin","name_zh":"插片选择销","name_ms":"","qty":"Universal stock","qty_zh":"通用库","qty_ms":"","cycle":"12 months","cycle_zh":"12个月","cycle_ms":""},
        {"name":"Spherical Bearing","name_zh":"关节轴承","name_ms":"","qty":"Universal stock","qty_zh":"通用库","qty_ms":"","cycle":"24-36 months","cycle_zh":"24-36个月","cycle_ms":""},
        {"name":"Handle Foam Grip","name_zh":"手柄海绵套","name_ms":"","qty":"Universal stock","qty_zh":"通用库","qty_ms":"","cycle":"6-12 months","cycle_zh":"6-12个月","cycle_ms":""},
        {"name":"Seat/Back Pad","name_zh":"座垫/靠垫","name_ms":"","qty":"Universal stock","qty_zh":"通用库","qty_ms":"","cycle":"18-24 months","cycle_zh":"18-24个月","cycle_ms":""},
    ],
    "schedule": [
        {"interval":"Daily","interval_zh":"每天","interval_ms":"","action":"Wipe sweat from seat pad","action_zh":"擦拭座垫汗渍","action_ms":""},
        {"interval":"Weekly","interval_zh":"每周","interval_ms":"","action":"Check weight pin","action_zh":"检查选择销","action_ms":""},
        {"interval":"Monthly","interval_zh":"每月","interval_ms":"","action":"Lubricate guide rods","action_zh":"导轨润滑","action_ms":""},
        {"interval":"Quarterly","interval_zh":"每季度","interval_ms":"","action":"Check pulleys and bearings","action_zh":"滑轮和轴承检查","action_ms":""},
        {"interval":"Semi-annually","interval_zh":"每半年","interval_ms":"","action":"Tighten all bolts","action_zh":"全机紧固","action_ms":""},
    ],
    "durability_note": "Flat chest press is one of the highest-usage machines. Diverging arm design distributes wear more evenly than linked designs, actually resulting in longer lifespan.",
    "durability_note_zh": "平卧推胸是使用频率最高的器械之一，分动臂设计比联动式磨损更均匀，寿命反而更长。",
    "durability_note_ms": "",
},

# ========================================
#  Plate-Loaded (PL-001 ~ PL-005)
# ========================================

"PL-001": {
    "badge": "full-kit",
    "badge_text": "Safety locks specially stocked",
    "badge_text_zh": "安全锁扣已重点备件",
    "badge_text_ms": "",
    "spare_parts": [
        {"name":"Linear Bearing","name_zh":"导轨滑块/线性轴承","name_ms":"","qty":"1 set (4 pcs)","qty_zh":"备1套(4个)","qty_ms":"","cycle":"24-36 months","cycle_zh":"24-36个月","cycle_ms":""},
        {"name":"Safety Lock/Ratchet","name_zh":"安全锁扣/棘爪","name_ms":"","qty":"2 pcs","qty_zh":"备2个","qty_ms":"","cycle":"12-18 months","cycle_zh":"12-18个月","cycle_ms":""},
        {"name":"Plate Post Sleeve","name_zh":"挂片柱套管","name_ms":"","qty":"2 pcs","qty_zh":"备2个","qty_ms":"","cycle":"36 months","cycle_zh":"36个月","cycle_ms":""},
        {"name":"Shoulder/Back Pad","name_zh":"肩垫/靠垫","name_ms":"","qty":"1 set","qty_zh":"备1套","qty_ms":"","cycle":"18-24 months","cycle_zh":"18-24个月","cycle_ms":""},
        {"name":"Footplate Anti-slip Surface","name_zh":"踏板防滑面层","name_ms":"","qty":"1 pc","qty_zh":"备1块","qty_ms":"","cycle":"12-18 months","cycle_zh":"12-18个月","cycle_ms":""},
    ],
    "schedule": [
        {"interval":"Daily","interval_zh":"每天","interval_ms":"","action":"Wipe sweat from back pad","action_zh":"擦拭靠垫汗渍","action_ms":""},
        {"interval":"Weekly","interval_zh":"每周","interval_ms":"","action":"Test safety lock engagement (SAFETY CRITICAL!)","action_zh":"测试安全锁扣锁定是否灵敏（安全关键！）","action_ms":""},
        {"interval":"Monthly","interval_zh":"每月","interval_ms":"","action":"Apply grease to guide rails","action_zh":"导轨涂润滑脂","action_ms":""},
        {"interval":"Quarterly","interval_zh":"每季度","interval_ms":"","action":"Tighten all bolts","action_zh":"紧固全机螺栓","action_ms":""},
    ],
    "durability_note": "Safety lock is the only high-frequency wear part on this machine — double quantity stocked. Guide rails are 45# steel with hard chrome plating, handling 160kg users doing repeated squats without deformation.",
    "durability_note_zh": "安全锁扣是这台器械唯一的高频易损件，已备双倍数量。导轨采用45#钢镀硬铬，承载160kg用户反复深蹲无变形。",
    "durability_note_ms": "",
},

"PL-002": {
    "badge": "full-kit",
    "badge_text": "Safety locks specially stocked",
    "badge_text_zh": "安全锁扣已重点备件",
    "badge_text_ms": "",
    "spare_parts": [
        {"name":"Guide Slider","name_zh":"导轨滑块","name_ms":"","qty":"1 set (4 pcs)","qty_zh":"备1套(4个)","qty_ms":"","cycle":"24-36 months","cycle_zh":"24-36个月","cycle_ms":""},
        {"name":"Safety Lock","name_zh":"安全锁扣","name_ms":"","qty":"2 pcs","qty_zh":"备2个","qty_ms":"","cycle":"12-18 months","cycle_zh":"12-18个月","cycle_ms":""},
        {"name":"Back Pad","name_zh":"靠垫/背垫","name_ms":"","qty":"1 pc","qty_zh":"备1个","qty_ms":"","cycle":"18-24 months","cycle_zh":"18-24个月","cycle_ms":""},
        {"name":"Footplate Surface","name_zh":"踏板防滑面层","name_ms":"","qty":"1 pc","qty_zh":"备1块","qty_ms":"","cycle":"12-18 months","cycle_zh":"12-18个月","cycle_ms":""},
    ],
    "schedule": [
        {"interval":"Daily","interval_zh":"每天","interval_ms":"","action":"Wipe back pad","action_zh":"擦拭靠垫","action_ms":""},
        {"interval":"Weekly","interval_zh":"每周","interval_ms":"","action":"Test safety lock","action_zh":"测试安全锁扣","action_ms":""},
        {"interval":"Monthly","interval_zh":"每月","interval_ms":"","action":"Lubricate guide rails","action_zh":"导轨润滑","action_ms":""},
        {"interval":"Quarterly","interval_zh":"每季度","interval_ms":"","action":"Tighten all bolts","action_zh":"全机紧固","action_ms":""},
    ],
    "durability_note": "Shares same spec safety locks with hack squat — mutual redundancy. Main frame uses 100×50mm rectangular steel tube, load capacity far exceeds rated value.",
    "durability_note_zh": "与哈克深蹲共用同规格安全锁扣备件，互为冗余。主体框架采用100×50mm矩形钢管，承载力远超额定值。",
    "durability_note_ms": "",
},

"PL-003": {
    "badge": "long-life",
    "badge_text": "All-steel construction · 10-year durability",
    "badge_text_zh": "纯钢结构 · 十年耐用",
    "badge_text_ms": "",
    "spare_parts": [
        {"name":"J-Hook","name_zh":"J-Hook杠铃托钩","name_ms":"","qty":"2 pairs from universal stock","qty_zh":"通用库备2对","qty_ms":"","cycle":"36+ months","cycle_zh":"36个月+","cycle_ms":""},
        {"name":"J-Hook Rubber Liner","name_zh":"J-Hook橡胶保护垫","name_ms":"","qty":"4 pairs from universal stock","qty_zh":"通用库备4对","qty_ms":"","cycle":"12 months","cycle_zh":"12个月","cycle_ms":""},
        {"name":"Bench Pad","name_zh":"靠垫","name_ms":"","qty":"1 pc","qty_zh":"备1个","qty_ms":"","cycle":"18-24 months","cycle_zh":"18-24个月","cycle_ms":""},
    ],
    "schedule": [
        {"interval":"Daily","interval_zh":"每天","interval_ms":"","action":"Wipe sweat from bench pad","action_zh":"擦拭靠垫汗渍","action_ms":""},
        {"interval":"Monthly","interval_zh":"每月","interval_ms":"","action":"Check J-Hook wear and locking","action_zh":"检查J-Hook磨损和锁定","action_ms":""},
        {"interval":"Quarterly","interval_zh":"每季度","interval_ms":"","action":"Inspect weld points, tighten all bolts","action_zh":"检查焊接点、紧固全机螺栓","action_ms":""},
    ],
    "durability_note": "No cables, no pulleys, no electronics — pure steel welded construction. The only things that wear are rubber pads and upholstery. J-Hook rubber liners are the only consumable, fully stocked. This machine will last until your next renovation.",
    "durability_note_zh": "没有钢丝绳、没有滑轮、没有电子件——纯钢焊接结构，能坏的只有橡胶垫和皮面。J-Hook橡胶垫是唯一消耗品，已备充足。这台器械可以用到你下一次装修。",
    "durability_note_ms": "",
},

"PL-004": {
    "badge": "long-life",
    "badge_text": "All-steel construction · 10-year durability",
    "badge_text_zh": "纯钢结构 · 十年耐用",
    "badge_text_ms": "",
    "spare_parts": [
        {"name":"J-Hook","name_zh":"J-Hook杠铃托钩","name_ms":"","qty":"Shared with PL-003 universal stock","qty_zh":"与PL-003共用通用库","qty_ms":"","cycle":"36+ months","cycle_zh":"36个月+","cycle_ms":""},
        {"name":"J-Hook Rubber Liner","name_zh":"J-Hook橡胶保护垫","name_ms":"","qty":"Shared universal stock","qty_zh":"共用通用库","qty_ms":"","cycle":"12 months","cycle_zh":"12个月","cycle_ms":""},
        {"name":"Bench Pad","name_zh":"靠垫","name_ms":"","qty":"1 pc","qty_zh":"备1个","qty_ms":"","cycle":"18-24 months","cycle_zh":"18-24个月","cycle_ms":""},
    ],
    "schedule": [
        {"interval":"Daily","interval_zh":"每天","interval_ms":"","action":"Wipe sweat from bench pad","action_zh":"擦拭靠垫汗渍","action_ms":""},
        {"interval":"Monthly","interval_zh":"每月","interval_ms":"","action":"Check J-Hook and angle lock","action_zh":"检查J-Hook和角度锁定","action_ms":""},
        {"interval":"Quarterly","interval_zh":"每季度","interval_ms":"","action":"Inspect weld points, tighten bolts","action_zh":"检查焊接点、紧固螺栓","action_ms":""},
    ],
    "durability_note": "Same as PL-003 — pure steel welded, zero electronics, zero cables. 250kg net weight is itself the best guarantee of stability.",
    "durability_note_zh": "同PL-003，纯钢焊接，零电子零绳索。净重250kg的自重本身就是稳定性的最好保证。",
    "durability_note_ms": "",
},

"PL-005": {
    "badge": "full-kit",
    "badge_text": "All 5 stations independently covered",
    "badge_text_zh": "5个工位备件独立覆盖",
    "badge_text_ms": "",
    "spare_parts": [
        {"name":"Coated Steel Cable","name_zh":"包胶钢丝绳","name_ms":"","qty":"Universal stock (1 per station × 5)","qty_zh":"通用库（5个工位各1根）","qty_ms":"","cycle":"18-24 months","cycle_zh":"18-24个月","cycle_ms":""},
        {"name":"Pulley w/ Bearing","name_zh":"滑轮（含轴承）","name_ms":"","qty":"Universal stock (10-12 pulleys for this unit)","qty_zh":"通用库（此机用10-12个）","qty_ms":"","cycle":"24-36 months","cycle_zh":"24-36个月","cycle_ms":""},
        {"name":"Weight Pin","name_zh":"插片选择销","name_ms":"","qty":"Universal stock (5 pcs)","qty_zh":"通用库（5个）","qty_ms":"","cycle":"12 months","cycle_zh":"12个月","cycle_ms":""},
        {"name":"Guide Rod Bushing","name_zh":"导轨塑料衬套","name_ms":"","qty":"Universal stock (5 sets)","qty_zh":"通用库（5套）","qty_ms":"","cycle":"12-18 months","cycle_zh":"12-18个月","cycle_ms":""},
        {"name":"Spherical Bearing","name_zh":"关节轴承","name_ms":"","qty":"Universal stock (10 pcs)","qty_zh":"通用库（10个）","qty_ms":"","cycle":"24-36 months","cycle_zh":"24-36个月","cycle_ms":""},
        {"name":"Handle Foam Grip","name_zh":"手柄海绵套","name_ms":"","qty":"Universal stock (5 sets)","qty_zh":"通用库（5套）","qty_ms":"","cycle":"6-12 months","cycle_zh":"6-12个月","cycle_ms":""},
        {"name":"Station Pads","name_zh":"各工位座垫/靠垫","name_ms":"","qty":"Universal stock (5 pcs)","qty_zh":"通用库（5个）","qty_ms":"","cycle":"18-24 months","cycle_zh":"18-24个月","cycle_ms":""},
    ],
    "schedule": [
        {"interval":"Daily","interval_zh":"每天","interval_ms":"","action":"Wipe seat pads at each station","action_zh":"逐工位擦拭座垫汗渍","action_ms":""},
        {"interval":"Weekly","interval_zh":"每周","interval_ms":"","action":"Check all 5 weight pins one by one","action_zh":"5个选择销逐一检查","action_ms":""},
        {"interval":"Monthly","interval_zh":"每月","interval_ms":"","action":"Lubricate all 5 guide rods one by one","action_zh":"5条导轨逐一润滑","action_ms":""},
        {"interval":"Quarterly","interval_zh":"每季度","interval_ms":"","action":"Inspect all pulleys and bearings one by one","action_zh":"所有滑轮和轴承逐一检查","action_ms":""},
        {"interval":"Semi-annually","interval_zh":"每半年","interval_ms":"","action":"Full bolt tightening (660kg unit — recommend 2-person operation)","action_zh":"全机紧固（660kg的大家伙，建议两人配合操作）","action_ms":""},
    ],
    "durability_note": "The 5-station is essentially 5 independent machines sharing one frame. Any one station having an issue doesn't affect the other four. 660kg self-weight — solid as a rock.",
    "durability_note_zh": "五人站本质是5台独立器械共享一个框架，任何一个工位出问题都不影响其他四个继续使用。660kg自重，稳如磐石。",
    "durability_note_ms": "",
},

# ========================================
#  Racks & Frames (RF-001 ~ RF-006)
# ========================================

"RF-001": {
    "badge": "full-kit",
    "badge_text": "Guide rail care kit shipped with equipment",
    "badge_text_zh": "导轨养护套件随货配送",
    "badge_text_ms": "",
    "spare_parts": [
        {"name":"Linear Bearing/Bushing","name_zh":"导轨线性轴承/铜套","name_ms":"","qty":"1 set (4 pcs)","qty_zh":"备1套(4个)","qty_ms":"","cycle":"24-36 months","cycle_zh":"24-36个月","cycle_ms":""},
        {"name":"Rotary Safety Lock","name_zh":"旋转锁扣","name_ms":"","qty":"1 pair","qty_zh":"备1对","qty_ms":"","cycle":"18-24 months","cycle_zh":"18-24个月","cycle_ms":""},
        {"name":"Bar Sleeve Bearing","name_zh":"杠铃套管轴承","name_ms":"","qty":"2 pcs","qty_zh":"备2个","qty_ms":"","cycle":"36 months","cycle_zh":"36个月","cycle_ms":""},
        {"name":"Rail Grease","name_zh":"导轨润滑脂","name_ms":"","qty":"Included in universal lube pack","qty_zh":"已含在通用润滑油包中","qty_ms":"","cycle":"Consumable","cycle_zh":"消耗品","cycle_ms":""},
    ],
    "schedule": [
        {"interval":"Before each use","interval_zh":"每次使用前","interval_ms":"","action":"Check rotary safety lock engagement (SAFETY CRITICAL!)","action_zh":"检查旋转锁扣是否正常锁定（安全关键！）","action_ms":""},
        {"interval":"Weekly","interval_zh":"每周","interval_ms":"","action":"Wipe guide rails and apply thin layer of grease","action_zh":"擦拭导轨并涂薄层润滑脂","action_ms":""},
        {"interval":"Monthly","interval_zh":"每月","interval_ms":"","action":"Check bar sleeve rotation smoothness","action_zh":"检查杠铃套管旋转顺滑度","action_ms":""},
        {"interval":"Quarterly","interval_zh":"每季度","interval_ms":"","action":"Check linear bearing/bushing wear","action_zh":"检查线性轴承/铜套磨损","action_ms":""},
        {"interval":"Semi-annually","interval_zh":"每半年","interval_ms":"","action":"Tighten all bolts","action_zh":"紧固全机螺栓","action_ms":""},
    ],
    "durability_note": "The Smith machine's core is its two guide rails — hard chrome plated with HRC65+ surface hardness. With normal maintenance, the rails themselves essentially never wear out. What wears is the bushing — replacing a bushing is as simple as changing a light bulb.",
    "durability_note_zh": "史密斯的核心是两根导轨——经过硬铬镀层处理，表面硬度HRC65以上，正常保养下导轨本身基本不会磨损，磨损的是铜套，换铜套就像换灯泡一样简单。",
    "durability_note_ms": "",
},

"RF-002": {
    "badge": "long-life",
    "badge_text": "All-steel welded · No wear parts",
    "badge_text_zh": "纯钢焊接 · 无易损件",
    "badge_text_ms": "",
    "spare_parts": [
        {"name":"J-Hook","name_zh":"J-Hook杠铃托钩","name_ms":"","qty":"Shared universal stock","qty_zh":"通用库共用","qty_ms":"","cycle":"36+ months","cycle_zh":"36个月+","cycle_ms":""},
        {"name":"J-Hook Rubber Liner","name_zh":"J-Hook橡胶保护垫","name_ms":"","qty":"Shared universal stock","qty_zh":"通用库共用","qty_ms":"","cycle":"12 months","cycle_zh":"12个月","cycle_ms":""},
        {"name":"Safety Spotter Arm","name_zh":"安全杠/保护臂","name_ms":"","qty":"1 pair from universal stock","qty_zh":"通用库备1对","qty_ms":"","cycle":"Rarely damaged","cycle_zh":"极少损坏","cycle_ms":""},
    ],
    "schedule": [
        {"interval":"Monthly","interval_zh":"每月","interval_ms":"","action":"Check J-Hook and safety arm locking hole wear","action_zh":"检查J-Hook和安全杠锁定孔位磨损","action_ms":""},
        {"interval":"Quarterly","interval_zh":"每季度","interval_ms":"","action":"Inspect weld points, tighten floor bolts","action_zh":"检查焊接点，紧固地脚螺栓","action_ms":""},
        {"interval":"Annually","interval_zh":"每年","interval_ms":"","action":"Touch up paint (if chipped or rusted)","action_zh":"补漆（如有掉漆或锈蚀）","action_ms":""},
    ],
    "durability_note": "Steel tubes welded together with no moving parts whatsoever. This is the least likely thing to break in a gym. Those 20-year-old hardcore gyms you see? The squat rack is always the original one.",
    "durability_note_zh": "一根根钢管焊在一起，没有任何运动部件。这是健身房里最不可能坏的东西。你看到那些用了20年还在用的老铁馆，深蹲架永远是最初那个。",
    "durability_note_ms": "",
},

"RF-003": {
    "badge": "long-life",
    "badge_text": "Solid wood + rubber · Occasional check only",
    "badge_text_zh": "实木+橡胶 · 只需偶尔检查",
    "badge_text_ms": "",
    "spare_parts": [],
    "schedule": [
        {"interval":"Monthly","interval_zh":"每月","interval_ms":"","action":"Check rubber surface for cracks or lifting","action_zh":"检查橡胶面层有无开裂或翘起","action_ms":""},
        {"interval":"Quarterly","interval_zh":"每季度","interval_ms":"","action":"Check wood board for warping","action_zh":"检查木板有无变形","action_ms":""},
        {"interval":"Annually","interval_zh":"每年","interval_ms":"","action":"Replace rubber surface if severely worn (procure rubber mat locally)","action_zh":"橡胶面层如严重磨损可整体更换（本地采购橡胶垫即可）","action_ms":""},
    ],
    "durability_note": "A wood board plus two rubber mats — no mechanical parts at all. Its job is to lie on the ground and be stepped on, which it can do for a lifetime.",
    "durability_note_zh": "一块木板加两块橡胶垫，没有任何机械部件。它的工作就是躺在地上被你踩，这件事它可以做一辈子。",
    "durability_note_ms": "",
},

"RF-004": {
    "badge": "long-life",
    "badge_text": "All-steel · Virtually maintenance-free",
    "badge_text_zh": "纯钢结构 · 基本免维护",
    "badge_text_ms": "",
    "spare_parts": [
        {"name":"Rubber Cradle Pad","name_zh":"橡胶托垫","name_ms":"","qty":"1 set","qty_zh":"备1套","qty_ms":"","cycle":"18-24 months","cycle_zh":"18-24个月","cycle_ms":""},
    ],
    "schedule": [
        {"interval":"Monthly","interval_zh":"每月","interval_ms":"","action":"Check weld points and foot stability","action_zh":"检查焊接点和底脚稳定性","action_ms":""},
        {"interval":"Semi-annually","interval_zh":"每半年","interval_ms":"","action":"Check rubber cradle pad wear, touch up paint","action_zh":"检查橡胶托垫磨损，补漆","action_ms":""},
    ],
    "durability_note": "Steel tube welded rack with load capacity far exceeding actual use. The only thing that breaks is the rubber cradle pad getting dented by dumbbells — just replace the pad.",
    "durability_note_zh": "钢管焊接架子，承重设计远超实际负载。唯一会坏的是橡胶托垫被哑铃砸凹，换垫即可。",
    "durability_note_ms": "",
},

"RF-005": {
    "badge": "long-life",
    "badge_text": "All-steel · Virtually maintenance-free",
    "badge_text_zh": "纯钢结构 · 基本免维护",
    "badge_text_ms": "",
    "spare_parts": [
        {"name":"Rubber Cradle Pad","name_zh":"橡胶托垫","name_ms":"","qty":"1 set","qty_zh":"备1套","qty_ms":"","cycle":"18-24 months","cycle_zh":"18-24个月","cycle_ms":""},
    ],
    "schedule": [
        {"interval":"Monthly","interval_zh":"每月","interval_ms":"","action":"Check weld points and feet","action_zh":"检查焊接点和底脚","action_ms":""},
        {"interval":"Semi-annually","interval_zh":"每半年","interval_ms":"","action":"Check rubber pads, touch up paint","action_zh":"检查橡胶垫，补漆","action_ms":""},
    ],
    "durability_note": "Same as RF-004 — steel tube rack, buy it and forget about it.",
    "durability_note_zh": "同RF-004，钢管架子，买回来就不用管它。",
    "durability_note_ms": "",
},

"RF-006": {
    "badge": "long-life",
    "badge_text": "No wear parts · Lifetime use",
    "badge_text_zh": "无易损件 · 终身使用",
    "badge_text_ms": "",
    "spare_parts": [],
    "schedule": [
        {"interval":"Semi-annually","interval_zh":"每半年","interval_ms":"","action":"Check weld points and foot stability","action_zh":"检查焊接点和底脚稳定性","action_ms":""},
        {"interval":"Annually","interval_zh":"每年","interval_ms":"","action":"Touch up paint where chipped to prevent rust","action_zh":"掉漆处补漆防锈","action_ms":""},
    ],
    "durability_note": "A few steel tubes welded into a tree shape to hold weight plates. There is simply no reason for this thing to break.",
    "durability_note_zh": "几根钢管焊成一棵树，上面挂铁片。这东西没有任何理由会坏。",
    "durability_note_ms": "",
},

# ========================================
#  Benches (BN-001 ~ BN-006)
# ========================================

"BN-001": {
    "badge": "long-life",
    "badge_text": "Steel + upholstery · Minimal structure",
    "badge_text_zh": "纯钢+皮面 · 极简结构",
    "badge_text_ms": "",
    "spare_parts": [
        {"name":"Seat Upholstery Pad","name_zh":"座面皮垫","name_ms":"","qty":"Not shipped — local reupholstery is more economical","qty_zh":"备件不随货，本地翻新更划算","qty_ms":"","cycle":"18-24 months","cycle_zh":"18-24个月","cycle_ms":""},
    ],
    "schedule": [
        {"interval":"Daily","interval_zh":"每天","interval_ms":"","action":"Wipe sweat from upholstery (sweat is PU leather's worst enemy)","action_zh":"擦拭皮面汗渍（汗液是PU皮最大的敌人）","action_ms":""},
        {"interval":"Monthly","interval_zh":"每月","interval_ms":"","action":"Check bolt tightness and foot pads","action_zh":"检查螺栓紧固和脚垫","action_ms":""},
        {"interval":"When cracked","interval_zh":"皮面开裂时","interval_ms":"","action":"Local sofa reupholstery shop, ~RM50-80 per pad","action_zh":"本地找沙发翻新店重新包皮，约RM50-80/张","action_ms":""},
    ],
    "durability_note": "A flat bench has zero adjustable mechanisms — one steel frame, one pad. The frame won't break. When the pad cracks, local reupholstery costs ten times less than shipping a new one from China.",
    "durability_note_zh": "水平训练椅没有任何可调机构——一个钢架一块垫子。钢架不会坏，垫子坏了本地包皮比从中国运一块新的便宜十倍。",
    "durability_note_ms": "",
},

"BN-002": {
    "badge": "long-life",
    "badge_text": "Simple structure · Minimal maintenance",
    "badge_text_zh": "简单结构 · 极少维护",
    "badge_text_ms": "",
    "spare_parts": [
        {"name":"Pad Upholstery","name_zh":"座面皮垫","name_ms":"","qty":"Local reupholstery","qty_zh":"本地翻新","qty_ms":"","cycle":"18-24 months","cycle_zh":"18-24个月","cycle_ms":""},
        {"name":"Foot Hook Foam","name_zh":"脚钩泡棉垫","name_ms":"","qty":"1 pair","qty_zh":"备1对","qty_ms":"","cycle":"12-18 months","cycle_zh":"12-18个月","cycle_ms":""},
    ],
    "schedule": [
        {"interval":"Daily","interval_zh":"每天","interval_ms":"","action":"Wipe sweat from upholstery","action_zh":"擦拭皮面汗渍","action_ms":""},
        {"interval":"Monthly","interval_zh":"每月","interval_ms":"","action":"Check angle adjustment lock and bolts","action_zh":"检查角度调节锁定和螺栓","action_ms":""},
    ],
    "durability_note": "Ab board has unidirectional loading and simple structure. The foot hook foam is the only wear part — spare shipped with equipment.",
    "durability_note_zh": "腹肌板受力方向单一，结构简单。脚钩泡棉是唯一会被磨损的部件，已随货配送备用。",
    "durability_note_ms": "",
},

"BN-003": {
    "badge": "long-life",
    "badge_text": "Adjustable · Focus on lock pin check",
    "badge_text_zh": "可调机构 · 重点检查锁销",
    "badge_text_ms": "",
    "spare_parts": [
        {"name":"Adjust Pin/Spring Lock","name_zh":"调节插销/弹簧锁销","name_ms":"","qty":"4 pcs from universal stock","qty_zh":"通用库备4个","qty_ms":"","cycle":"12-18 months","cycle_zh":"12-18个月","cycle_ms":""},
        {"name":"Pad Upholstery","name_zh":"座面皮垫","name_ms":"","qty":"Local reupholstery","qty_zh":"本地翻新","qty_ms":"","cycle":"18-24 months","cycle_zh":"18-24个月","cycle_ms":""},
    ],
    "schedule": [
        {"interval":"Daily","interval_zh":"每天","interval_ms":"","action":"Wipe sweat from upholstery","action_zh":"擦拭皮面汗渍","action_ms":""},
        {"interval":"Weekly","interval_zh":"每周","interval_ms":"","action":"Check angle lock pin spring return","action_zh":"检查角度锁销弹簧回弹是否正常","action_ms":""},
        {"interval":"Monthly","interval_zh":"每月","interval_ms":"","action":"Check all bolt tightness","action_zh":"检查所有螺栓紧固度","action_ms":""},
    ],
    "durability_note": "The most common issue with adjustable benches is lock pin spring fatigue — universal stock has ample replacement pins. 30-second self-replacement.",
    "durability_note_zh": "可调凳最常见的问题就是锁销弹簧疲劳——通用库已备足替换锁销，30秒自行更换。",
    "durability_note_ms": "",
},

"BN-004": {
    "badge": "long-life",
    "badge_text": "Fixed angle · No adjustable parts",
    "badge_text_zh": "固定角度 · 无可调机构",
    "badge_text_ms": "",
    "spare_parts": [
        {"name":"Pad Upholstery","name_zh":"座面皮垫","name_ms":"","qty":"Local reupholstery","qty_zh":"本地翻新","qty_ms":"","cycle":"18-24 months","cycle_zh":"18-24个月","cycle_ms":""},
    ],
    "schedule": [
        {"interval":"Daily","interval_zh":"每天","interval_ms":"","action":"Wipe sweat from upholstery","action_zh":"擦拭皮面汗渍","action_ms":""},
        {"interval":"Quarterly","interval_zh":"每季度","interval_ms":"","action":"Inspect weld points and bolts","action_zh":"检查焊接点和螺栓","action_ms":""},
    ],
    "durability_note": "Fixed 75-degree angle with no adjustment mechanism — eliminates the only failure point found in adjustable benches. Steel frame for lifetime use, upholstery reupholstered locally.",
    "durability_note_zh": "75度固定角度，没有任何调节机构，比可调凳少了唯一的故障点。钢架终身使用，皮面本地翻新。",
    "durability_note_ms": "",
},

"BN-005": {
    "badge": "long-life",
    "badge_text": "Adjustable · Focus on lock pin check",
    "badge_text_zh": "可调机构 · 重点检查锁销",
    "badge_text_ms": "",
    "spare_parts": [
        {"name":"Adjust Pin/Spring Lock","name_zh":"调节插销/弹簧锁销","name_ms":"","qty":"Shared universal stock","qty_zh":"通用库共用","qty_ms":"","cycle":"12-18 months","cycle_zh":"12-18个月","cycle_ms":""},
        {"name":"Pad Upholstery","name_zh":"座面皮垫","name_ms":"","qty":"Local reupholstery","qty_zh":"本地翻新","qty_ms":"","cycle":"18-24 months","cycle_zh":"18-24个月","cycle_ms":""},
    ],
    "schedule": [
        {"interval":"Daily","interval_zh":"每天","interval_ms":"","action":"Wipe sweat from upholstery","action_zh":"擦拭皮面汗渍","action_ms":""},
        {"interval":"Weekly","interval_zh":"每周","interval_ms":"","action":"Check all angle lock pin springs","action_zh":"检查各角度锁销弹簧","action_ms":""},
        {"interval":"Monthly","interval_zh":"每月","interval_ms":"","action":"Tighten bolts","action_zh":"紧固螺栓","action_ms":""},
    ],
    "durability_note": "FID multi-angle adjustable — lock pin is the only moving part, fully stocked in universal inventory. Just wipe sweat daily and press the lock pins weekly.",
    "durability_note_zh": "FID多角度可调，锁销是唯一活动部件，通用库已备足。日常只要每天擦汗、每周按一按锁销就行了。",
    "durability_note_ms": "",
},

"BN-006": {
    "badge": "long-life",
    "badge_text": "Steel + upholstery · Minimal structure",
    "badge_text_zh": "纯钢+皮面 · 极简结构",
    "badge_text_ms": "",
    "spare_parts": [
        {"name":"Hip/Leg Pad","name_zh":"髋垫/腿固定垫","name_ms":"","qty":"1 pc","qty_zh":"备1个","qty_ms":"","cycle":"18-24 months","cycle_zh":"18-24个月","cycle_ms":""},
    ],
    "schedule": [
        {"interval":"Daily","interval_zh":"每天","interval_ms":"","action":"Wipe sweat from contact surfaces","action_zh":"擦拭接触面汗渍","action_ms":""},
        {"interval":"Monthly","interval_zh":"每月","interval_ms":"","action":"Check height adjustment holes and lock pin","action_zh":"检查高度调节孔位和锁销","action_ms":""},
        {"interval":"Quarterly","interval_zh":"每季度","interval_ms":"","action":"Tighten bolts","action_zh":"紧固螺栓","action_ms":""},
    ],
    "durability_note": "Structure is as simple as the ab board. 96kg self-weight ensures even the heaviest members won't budge it during back extensions.",
    "durability_note_zh": "结构跟腹肌板一样简单。96kg的自重保证了再大体重的会员做背部伸展也纹丝不动。",
    "durability_note_ms": "",
},

# ========================================
#  Free Weights (FW-001 ~ FW-007)
# ========================================

"FW-001": {
    "badge": "long-life",
    "badge_text": "Solid cast iron · No mechanical parts",
    "badge_text_zh": "实心铸铁 · 无机械部件",
    "badge_text_ms": "",
    "spare_parts": [],
    "schedule": [
        {"interval":"Monthly","interval_zh":"每月","interval_ms":"","action":"Check rubber coating/chrome plating for peeling, tighten loose dumbbell heads","action_zh":"检查包胶/电镀是否脱落，松动的哑铃头及时紧固","action_ms":""},
        {"interval":"Quarterly","interval_zh":"每季度","interval_ms":"","action":"Clean with damp cloth, store dry","action_zh":"用湿布清洁，干燥存放","action_ms":""},
    ],
    "durability_note": "A block of iron. It existed before your gym and will continue to exist after. There is no maintenance schedule because iron doesn't expire.",
    "durability_note_zh": "一块铁。它在你之前的健身房存在，也会在你之后继续存在。没有保养周期，因为铁不会过期。",
    "durability_note_ms": "",
},

"FW-002": {
    "badge": "long-life",
    "badge_text": "Solid cast iron · No mechanical parts",
    "badge_text_zh": "实心铸铁 · 无机械部件",
    "badge_text_ms": "",
    "spare_parts": [],
    "schedule": [
        {"interval":"Monthly","interval_zh":"每月","interval_ms":"","action":"Check rubber coating/chrome plating","action_zh":"检查包胶/电镀层","action_ms":""},
        {"interval":"Quarterly","interval_zh":"每季度","interval_ms":"","action":"Clean, tighten threads","action_zh":"清洁，紧固螺纹","action_ms":""},
    ],
    "durability_note": "Same as FW-001. A heavier block of iron.",
    "durability_note_zh": "同FW-001。一块更重的铁。",
    "durability_note_ms": "",
},

"FW-003": {
    "badge": "long-life",
    "badge_text": "Cast iron plates · No mechanical parts",
    "badge_text_zh": "铸铁片 · 无机械部件",
    "badge_text_ms": "",
    "spare_parts": [],
    "schedule": [
        {"interval":"Quarterly","interval_zh":"每季度","interval_ms":"","action":"Check for cracks (cast iron plates can crack in extreme cases), clean surface","action_zh":"检查有无裂纹（铸铁片极端情况下可能开裂），清洁表面","action_ms":""},
    ],
    "durability_note": "Cast iron weight plates from last century are still in use everywhere. Just keep them dry to prevent rust. If they do rust, sand them down and keep going.",
    "durability_note_zh": "铸铁杠铃片从上世纪用到现在的比比皆是。保持干燥不生锈就行，实在生锈了砂纸打一打继续用。",
    "durability_note_ms": "",
},

"FW-004": {
    "badge": "long-life",
    "badge_text": "Cast iron plates · No mechanical parts",
    "badge_text_zh": "铸铁片 · 无机械部件",
    "badge_text_ms": "",
    "spare_parts": [],
    "schedule": [
        {"interval":"Quarterly","interval_zh":"每季度","interval_ms":"","action":"Check for cracks, clean surface","action_zh":"检查裂纹，清洁表面","action_ms":""},
    ],
    "durability_note": "Same as FW-003.",
    "durability_note_zh": "同FW-003。",
    "durability_note_ms": "",
},

"FW-005": {
    "badge": "full-kit",
    "badge_text": "Bearings & bushings included",
    "badge_text_zh": "轴承+铜套备件已配送",
    "badge_text_ms": "",
    "spare_parts": [
        {"name":"Bearing","name_zh":"轴承","name_ms":"","qty":"4 pcs for 4 bars","qty_zh":"4根杆共备4个","qty_ms":"","cycle":"24-36 months","cycle_zh":"24-36个月","cycle_ms":""},
        {"name":"Bronze Bushing","name_zh":"铜套","name_ms":"","qty":"4 pcs for 4 bars","qty_zh":"4根杆共备4个","qty_ms":"","cycle":"24-36 months","cycle_zh":"24-36个月","cycle_ms":""},
        {"name":"Snap Ring","name_zh":"卡簧","name_ms":"","qty":"8 pcs","qty_zh":"备8个","qty_ms":"","cycle":"12 months","cycle_zh":"12个月","cycle_ms":""},
    ],
    "schedule": [
        {"interval":"Weekly","interval_zh":"每周","interval_ms":"","action":"Wipe bar shaft with 3-IN-ONE oil to prevent rust","action_zh":"用3-IN-ONE油擦拭杆身防锈","action_ms":""},
        {"interval":"Monthly","interval_zh":"每月","interval_ms":"","action":"Spin sleeves to check bearing smoothness","action_zh":"转动套筒检查轴承顺滑度","action_ms":""},
        {"interval":"Quarterly","interval_zh":"每季度","interval_ms":"","action":"Disassemble sleeves, clean old grease, re-apply bearing grease","action_zh":"拆开套筒清洁旧油脂，重新注入轴承润滑脂","action_ms":""},
    ],
    "durability_note": "45# steel bar balances hardness and elasticity — bar shaft essentially won't bend or deform under commercial use. Bearings and bushings are the only consumables, fully stocked. Self-replacement difficulty is equivalent to changing a bicycle tire.",
    "durability_note_zh": "45#钢杆身硬度和弹性兼顾，商用环境下杆身本体基本不会弯曲变形。轴承和铜套是唯一消耗件，已备足，自行更换难度等同于换自行车轮胎。",
    "durability_note_ms": "",
},

"FW-006": {
    "badge": "full-kit",
    "badge_text": "Bearings & bushings included",
    "badge_text_zh": "轴承+铜套备件已配送",
    "badge_text_ms": "",
    "spare_parts": [
        {"name":"Bearing","name_zh":"轴承","name_ms":"","qty":"2 pcs","qty_zh":"备2个","qty_ms":"","cycle":"24-36 months","cycle_zh":"24-36个月","cycle_ms":""},
        {"name":"Bronze Bushing","name_zh":"铜套","name_ms":"","qty":"2 pcs","qty_zh":"备2个","qty_ms":"","cycle":"24-36 months","cycle_zh":"24-36个月","cycle_ms":""},
        {"name":"Snap Ring","name_zh":"卡簧","name_ms":"","qty":"2 pcs","qty_zh":"备2个","qty_ms":"","cycle":"12 months","cycle_zh":"12个月","cycle_ms":""},
    ],
    "schedule": [
        {"interval":"Weekly","interval_zh":"每周","interval_ms":"","action":"Wipe bar shaft to prevent rust","action_zh":"擦拭杆身防锈","action_ms":""},
        {"interval":"Quarterly","interval_zh":"每季度","interval_ms":"","action":"Clean sleeves, re-apply grease","action_zh":"套筒清洁注脂","action_ms":""},
    ],
    "durability_note": "Dual bearing + dual bronze bushing design — smoother and more durable than single-bearing bars.",
    "durability_note_zh": "双轴承双铜套设计，比单轴承杆更顺滑更耐用。",
    "durability_note_ms": "",
},

"FW-007": {
    "badge": "full-kit",
    "badge_text": "Bearings & bushings included",
    "badge_text_zh": "轴承+铜套备件已配送",
    "badge_text_ms": "",
    "spare_parts": [
        {"name":"Bearing","name_zh":"轴承","name_ms":"","qty":"2 pcs","qty_zh":"备2个","qty_ms":"","cycle":"24-36 months","cycle_zh":"24-36个月","cycle_ms":""},
        {"name":"Bronze Bushing","name_zh":"铜套","name_ms":"","qty":"2 pcs","qty_zh":"备2个","qty_ms":"","cycle":"24-36 months","cycle_zh":"24-36个月","cycle_ms":""},
        {"name":"Snap Ring","name_zh":"卡簧","name_ms":"","qty":"2 pcs","qty_zh":"备2个","qty_ms":"","cycle":"12 months","cycle_zh":"12个月","cycle_ms":""},
    ],
    "schedule": [
        {"interval":"Weekly","interval_zh":"每周","interval_ms":"","action":"Wipe bar shaft to prevent rust","action_zh":"擦拭杆身防锈","action_ms":""},
        {"interval":"Quarterly","interval_zh":"每季度","interval_ms":"","action":"Clean sleeves, re-apply grease","action_zh":"套筒清洁注脂","action_ms":""},
    ],
    "durability_note": "Same as FW-006. The EZ curl bar's curved section is single-piece forged, not bent after the fact — no risk of stress fracture.",
    "durability_note_zh": "同FW-006。EZ曲杆的弯曲部分是一体锻造的，不是后期弯折的，不存在应力断裂风险。",
    "durability_note_ms": "",
},

# ========================================
#  Functional Training (FT-001 ~ FT-012)
# ========================================

"FT-001": {
    "badge": "long-life",
    "badge_text": "Single-piece cast · No removable parts",
    "badge_text_zh": "整体铸造 · 无可拆部件",
    "badge_text_ms": "",
    "spare_parts": [],
    "schedule": [
        {"interval":"Monthly","interval_zh":"每月","interval_ms":"","action":"Check handle weld points and powder coating","action_zh":"检查把手焊接点和喷塑层","action_ms":""},
        {"interval":"Quarterly","interval_zh":"每季度","interval_ms":"","action":"Clean surface, store dry","action_zh":"清洁表面，干燥存放","action_ms":""},
    ],
    "durability_note": "A block of iron with a handle. Can't break it, can't smash it, can't use it up.",
    "durability_note_zh": "一块带把手的铁。摔不坏，砸不烂，用不完。",
    "durability_note_ms": "",
},

"FT-002": {
    "badge": "long-life",
    "badge_text": "Steel rack · Maintenance-free",
    "badge_text_zh": "钢架 · 免维护",
    "badge_text_ms": "",
    "spare_parts": [],
    "schedule": [
        {"interval":"Semi-annually","interval_zh":"每半年","interval_ms":"","action":"Check stability and weld points","action_zh":"检查稳定性和焊接点","action_ms":""},
    ],
    "durability_note": "A rack for holding kettlebells — even harder to break than the kettlebells themselves.",
    "durability_note_zh": "放壶铃的架子，比壶铃还不容易坏。",
    "durability_note_ms": "",
},

"FT-003": {
    "badge": "consumable",
    "badge_text": "Consumable · Replace on schedule",
    "badge_text_zh": "消耗品 · 按周期整体更换",
    "badge_text_ms": "",
    "spare_parts": [],
    "schedule": [
        {"interval":"Monthly","interval_zh":"每月","interval_ms":"","action":"Check skin for cracks or delamination","action_zh":"检查外皮有无开裂、脱胶","action_ms":""},
        {"interval":"12-24 months","interval_zh":"12-24个月","interval_ms":"","action":"Replace entirely when skin is severely cracked (available locally or from China)","action_zh":"外皮严重开裂时整体更换（本地或中国采购均可）","action_ms":""},
    ],
    "durability_note": "Medicine balls are the only training tool with a true \"lifespan.\" Skin cracking is normal — it means your members are training hard. Available at any local sports shop, no need to import from China.",
    "durability_note_zh": "药球是唯一有「寿命」的训练工具。外皮开裂是正常现象，说明你的会员在认真练。本地体育用品店随时可以补货，无需从中国进口。",
    "durability_note_ms": "",
},

"FT-004": {
    "badge": "long-life",
    "badge_text": "Steel rack · Maintenance-free",
    "badge_text_zh": "钢架 · 免维护",
    "badge_text_ms": "",
    "spare_parts": [],
    "schedule": [
        {"interval":"Semi-annually","interval_zh":"每半年","interval_ms":"","action":"Check stability","action_zh":"检查稳定性","action_ms":""},
    ],
    "durability_note": "Same as kettlebell rack — a rack for holding things has no reason to break.",
    "durability_note_zh": "同壶铃架，放东西的架子没有坏的理由。",
    "durability_note_ms": "",
},

"FT-005": {
    "badge": "consumable",
    "badge_text": "Consumable · Replace on schedule",
    "badge_text_zh": "消耗品 · 按周期整体更换",
    "badge_text_ms": "",
    "spare_parts": [
        {"name":"Wall Anchor Bolt","name_zh":"墙面锚点螺栓","name_ms":"","qty":"2 sets","qty_zh":"备2套","qty_ms":"","cycle":"Check quarterly","cycle_zh":"每季度检查","cycle_ms":""},
    ],
    "schedule": [
        {"interval":"Monthly","interval_zh":"每月","interval_ms":"","action":"Check rope end bindings for looseness","action_zh":"检查绳头绑带是否松散","action_ms":""},
        {"interval":"Quarterly","interval_zh":"每季度","interval_ms":"","action":"Check wall anchor bolt tightness","action_zh":"检查墙面锚点螺栓紧固","action_ms":""},
        {"interval":"12-18 months","interval_zh":"12-18个月","interval_ms":"","action":"Replace entire rope when frayed (available locally)","action_zh":"绳体磨损起毛时整体更换（本地采购即可）","action_ms":""},
    ],
    "durability_note": "Battle rope lifespan depends on the floor — thicker, smoother gym flooring means slower rope wear. Anchor bolts are safety-critical parts, fully stocked. The rope itself is inexpensive and available at Decathlon anytime.",
    "durability_note_zh": "战绳的寿命取决于地面——如果地胶够厚够滑，绳子磨损就慢。锚点螺栓是安全关键件，已备足替换。绳子本身不贵，本地Decathlon随时买得到。",
    "durability_note_ms": "",
},

"FT-006": {
    "badge": "consumable",
    "badge_text": "Webbing product · Regular stitch inspection",
    "badge_text_zh": "织带制品 · 定期检查缝线",
    "badge_text_ms": "",
    "spare_parts": [
        {"name":"Ceiling Anchor + Carabiner","name_zh":"天花锚点螺栓+扣环","name_ms":"","qty":"3 sets","qty_zh":"备3套","qty_ms":"","cycle":"Check quarterly","cycle_zh":"每季度检查","cycle_ms":""},
    ],
    "schedule": [
        {"interval":"Monthly","interval_zh":"每月","interval_ms":"","action":"Check stitching for looseness, webbing for wear","action_zh":"检查缝线有无松脱，织带有无磨损","action_ms":""},
        {"interval":"Quarterly","interval_zh":"每季度","interval_ms":"","action":"Check ceiling anchor bolts and carabiners","action_zh":"检查天花锚点螺栓和扣环","action_ms":""},
        {"interval":"12-18 months","interval_zh":"12-18个月","interval_ms":"","action":"Replace entirely when webbing is worn or stitching is loose","action_zh":"织带出现磨损或缝线松脱时整体更换","action_ms":""},
    ],
    "durability_note": "TRX is a load-bearing webbing — members' full body weight hangs from it. Safety first. Just inspect stitching carefully each month. Normal use lasts 1+ year easily. Anchor bolts fully stocked.",
    "durability_note_zh": "TRX是承重织带，会员全身重量悬挂在上面，安全第一。每月认真检查缝线就好，正常使用1年以上没问题。锚点螺栓已备足。",
    "durability_note_ms": "",
},

"FT-007": {
    "badge": "consumable",
    "badge_text": "Rubber product · Periodic replacement",
    "badge_text_zh": "橡胶制品 · 定期更换",
    "badge_text_ms": "",
    "spare_parts": [],
    "schedule": [
        {"interval":"Monthly","interval_zh":"每月","interval_ms":"","action":"Check for cracks, elasticity loss","action_zh":"检查有无裂纹、弹性衰减","action_ms":""},
        {"interval":"6-12 months","interval_zh":"6-12个月","interval_ms":"","action":"Replace entire set when elasticity drops noticeably or cracks appear","action_zh":"弹性明显下降或出现裂纹时整套更换","action_ms":""},
    ],
    "durability_note": "Resistance bands are rubber products that naturally age. The good news: they're among the cheapest training tools — a set costs under RM30. Order on Shopee for next-day delivery. Not worth shipping from China.",
    "durability_note_zh": "弹力带是橡胶制品，天然会老化。好消息是它也是最便宜的训练工具之一——一套不到RM30，本地Shopee随时下单次日到。不值得从中国运。",
    "durability_note_ms": "",
},

"FT-008": {
    "badge": "consumable",
    "badge_text": "Consumable · Replace per hygiene standard",
    "badge_text_zh": "消耗品 · 按卫生标准更换",
    "badge_text_ms": "",
    "spare_parts": [],
    "schedule": [
        {"interval":"Daily","interval_zh":"每天","interval_ms":"","action":"Spray disinfectant and wipe after use (sweat + bacteria are a mat's #1 killer)","action_zh":"使用后喷消毒液擦拭（汗渍+细菌是垫子的头号杀手）","action_ms":""},
        {"interval":"12-18 months","interval_zh":"12-18个月","interval_ms":"","action":"Replace when surface cracks or odor cannot be removed","action_zh":"表面开裂、异味无法清除时整体更换","action_ms":""},
    ],
    "durability_note": "Exercise mats are hygiene consumables — even the best mat should be replaced after a year or so. Available at Mr. DIY / Decathlon anytime, under RM20 each.",
    "durability_note_zh": "训练垫是卫生消耗品，再好的垫子用一年多也该换了。本地Mr. DIY / Decathlon随时有货，每张不到RM20。",
    "durability_note_ms": "",
},

"FT-009": {
    "badge": "consumable",
    "badge_text": "Consumable · Replace when deformed",
    "badge_text_zh": "消耗品 · 变形即换",
    "badge_text_ms": "",
    "spare_parts": [],
    "schedule": [
        {"interval":"Monthly","interval_zh":"每月","interval_ms":"","action":"Check for collapse or deformation","action_zh":"检查有无塌陷变形","action_ms":""},
        {"interval":"12-18 months","interval_zh":"12-18个月","interval_ms":"","action":"Replace when resilience noticeably decreases","action_zh":"回弹性明显下降时更换","action_ms":""},
    ],
    "durability_note": "Foam rollers get compressed flat over time — that's normal. Search \"foam roller\" on Shopee — RM15-30 each. Not worth international shipping.",
    "durability_note_zh": "泡沫轴用久了会被压扁变形，这是正常的。本地Shopee搜\"foam roller\"一大把，RM15-30一根，不值得跨国运输。",
    "durability_note_ms": "",
},

"FT-010": {
    "badge": "long-life",
    "badge_text": "Plywood construction · Impact resistant",
    "badge_text_zh": "多层板结构 · 耐冲击",
    "badge_text_ms": "",
    "spare_parts": [
        {"name":"Anti-slip Surface","name_zh":"防滑面层","name_ms":"","qty":"Can be replaced with local anti-slip tape","qty_zh":"可本地采购防滑贴替换","qty_ms":"","cycle":"12-18 months","cycle_zh":"12-18个月","cycle_ms":""},
    ],
    "schedule": [
        {"interval":"Monthly","interval_zh":"每月","interval_ms":"","action":"Check edges and anti-slip surface integrity","action_zh":"检查棱角和防滑面是否完好","action_ms":""},
        {"interval":"12-18 months","interval_zh":"12-18个月","interval_ms":"","action":"Re-apply anti-slip surface when worn (buy anti-slip sandpaper tape at local hardware store)","action_zh":"防滑面磨损时重新粘贴（本地五金店买防滑砂纸贴即可）","action_ms":""},
    ],
    "durability_note": "3-in-1 plyo box made from 18mm plywood — handles repeated jumping impacts. The wood itself won't break. Anti-slip surface is the only consumable — RM10 per roll of anti-slip tape at any hardware store.",
    "durability_note_zh": "3合1跳箱用18mm多层板制作，能承受反复跳跃冲击。木头本身不会坏，防滑面是唯一消耗面，本地五金店的防滑砂纸贴RM10一卷搞定。",
    "durability_note_ms": "",
},

"FT-011": {
    "badge": "long-life",
    "badge_text": "Wall-mounted steel · Focus on bolt check",
    "badge_text_zh": "壁挂钢架 · 重点检查螺栓",
    "badge_text_ms": "",
    "spare_parts": [
        {"name":"Wall Bolt","name_zh":"壁挂螺栓","name_ms":"","qty":"1 set","qty_zh":"备1套","qty_ms":"","cycle":"Check quarterly","cycle_zh":"每季度检查","cycle_ms":""},
        {"name":"Grip Cover","name_zh":"握把套","name_ms":"","qty":"1 pc","qty_zh":"备1个","qty_ms":"","cycle":"12 months","cycle_zh":"12个月","cycle_ms":""},
    ],
    "schedule": [
        {"interval":"Monthly","interval_zh":"每月","interval_ms":"","action":"Check wall bolts for looseness (SAFETY CRITICAL!)","action_zh":"检查壁挂螺栓有无松动（安全关键！）","action_ms":""},
        {"interval":"Quarterly","interval_zh":"每季度","interval_ms":"","action":"Tighten all bolts","action_zh":"拧紧所有螺栓","action_ms":""},
        {"interval":"12 months","interval_zh":"12个月","interval_ms":"","action":"Replace grip cover when worn","action_zh":"握把套磨损时更换","action_ms":""},
    ],
    "durability_note": "The steel frame itself won't break — the key is wall anchoring. Must be installed on load-bearing wall/concrete with M12+ expansion bolts. Once installed, just check bolts regularly.",
    "durability_note_zh": "钢架本身不会坏，关键是墙面锚固。安装时必须打在承重墙/混凝土墙上，膨胀螺栓用M12以上规格。装好之后定期检查螺栓就行。",
    "durability_note_ms": "",
},

"FT-012": {
    "badge": "long-life",
    "badge_text": "Rubber tire · Lifetime use",
    "badge_text_zh": "橡胶轮胎 · 终身使用",
    "badge_text_ms": "",
    "spare_parts": [],
    "schedule": [],
    "durability_note": "This is a tire. It survived hundreds of thousands of kilometers on a truck in its previous life. Being flipped around in your gym is retirement. Zero maintenance required.",
    "durability_note_zh": "这是一个轮胎。它上辈子在卡车上跑了几十万公里都没坏，在你的健身房里被翻来翻去对它来说是退休生活。无需任何维护。",
    "durability_note_ms": "",
},

# ========================================
#  Accessories (AC-001 ~ AC-004)
# ========================================

"AC-001": {
    "badge": "long-life",
    "badge_text": "EPDM rubber · 5+ year lifespan",
    "badge_text_zh": "EPDM橡胶 · 5年以上寿命",
    "badge_text_ms": "",
    "spare_parts": [],
    "schedule": [
        {"interval":"Daily","interval_zh":"每天","interval_ms":"","action":"Sweep dust, wet mop clean","action_zh":"清扫灰尘，湿拖清洁","action_ms":""},
        {"interval":"Monthly","interval_zh":"每月","interval_ms":"","action":"Check interlocking seams for lifting","action_zh":"检查拼接缝有无翘起","action_ms":""},
        {"interval":"Annually","interval_zh":"每年","interval_ms":"","action":"Replace damaged tiles individually (recommend buying 5% extra at opening for spares)","action_zh":"局部破损处可单块替换（建议开业时多买5%余量备用）","action_ms":""},
    ],
    "durability_note": "EPDM rubber flooring is UV-resistant, wear-resistant, and sweat-corrosion resistant. Normal lifespan is 5-8 years. Procure locally — recommend buying 5% extra as future replacement stock.",
    "durability_note_zh": "EPDM橡胶地胶耐紫外线、耐磨、耐汗液腐蚀，正常使用寿命5-8年。本地采购，建议多买5%作为日后局部替换备用。",
    "durability_note_ms": "",
},

"AC-002": {
    "badge": "long-life",
    "badge_text": "20mm heavy-duty · Designed for barbell drops",
    "badge_text_zh": "20mm加厚 · 专为杠铃落地设计",
    "badge_text_ms": "",
    "spare_parts": [],
    "schedule": [
        {"interval":"Monthly","interval_zh":"每月","interval_ms":"","action":"Check deadlift/squat area for dents or cracks","action_zh":"检查硬拉/深蹲区有无砸凹或开裂","action_ms":""},
        {"interval":"Annually","interval_zh":"每年","interval_ms":"","action":"Replace severely damaged sections individually","action_zh":"重度损伤区域单块替换","action_ms":""},
    ],
    "durability_note": "20mm high-density rubber specifically designed for barbell deadlift drop impact. Shorter lifespan than 10mm standard flooring (3-5 years), but it protects your floor and your downstairs neighbor's ceiling.",
    "durability_note_zh": "20mm高密度橡胶专门承受杠铃硬拉落地冲击。比10mm常规地胶寿命短一些（3-5年），但它保护的是你的地面和楼下邻居的天花板。",
    "durability_note_ms": "",
},

"AC-003": {
    "badge": "long-life",
    "badge_text": "Safety mirror · Shatter-proof film",
    "badge_text_zh": "安全银镜 · 防爆贴膜",
    "badge_text_ms": "",
    "spare_parts": [],
    "schedule": [
        {"interval":"Daily","interval_zh":"每天","interval_ms":"","action":"Clean fingerprints and sweat with glass cleaner","action_zh":"玻璃清洁剂擦拭指纹和汗渍","action_ms":""},
        {"interval":"Monthly","interval_zh":"每月","interval_ms":"","action":"Check corner mounting for looseness","action_zh":"检查边角固定是否松动","action_ms":""},
    ],
    "durability_note": "5mm safety mirror with shatter-proof film — even if hit by a dumbbell, it only cracks without scattering fragments. Won't break under normal use. The only enemy is flying dumbbells — keep mirrors at least 3 meters from dumbbell racks.",
    "durability_note_zh": "5mm安全银镜贴了防爆膜，即使被哑铃砸中也只会裂纹不会碎片飞溅。正常使用不会坏，唯一的敌人是飞出去的哑铃——所以哑铃区镜子要离墙面架子至少3米。",
    "durability_note_ms": "",
},

"AC-004": {
    "badge": "long-life",
    "badge_text": "Cold-rolled steel · Minimal maintenance",
    "badge_text_zh": "冷轧钢板 · 极少维护",
    "badge_text_ms": "",
    "spare_parts": [],
    "schedule": [
        {"interval":"Monthly","interval_zh":"每月","interval_ms":"","action":"Check door hinges and locks","action_zh":"检查门铰和锁具","action_ms":""},
        {"interval":"Quarterly","interval_zh":"每季度","interval_ms":"","action":"Apply small amount of lubricant to hinges to prevent rust (high humidity in Malaysia)","action_zh":"给铰链加少量润滑油防生锈（马来西亚湿度高）","action_ms":""},
    ],
    "durability_note": "Steel lockers need rust prevention attention in Malaysia's humid environment. A little WD-40 on hinges each quarter is all it takes — the cabinet body itself will last 10+ years.",
    "durability_note_zh": "钢制储物柜在马来西亚的潮湿环境下需要注意防锈。门铰每季度加一点WD-40就好，柜体本身10年不会有问题。",
    "durability_note_ms": "",
},

}  # end MAINTENANCE
